package io.tr8.yybijika.data

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import io.tr8.yybijika.exercise.CharacterPart
import io.tr8.yybijika.exercise.ExampleSentence
import io.tr8.yybijika.exercise.Relation
import io.tr8.yybijika.exercise.WordBundle
import java.io.File

/**
 * Read-only access to the deck that ships with the app.
 *
 * content.db is generated by the Python pipeline, so its schema is defined in
 * pipeline/schema.sql rather than in Kotlin. Reading it with plain SQLite rather
 * than Room is deliberate: Room would want to own the schema and verify it on
 * open, which turns every pipeline change into a migration argument with a file
 * nobody migrates — it is replaced wholesale on each release.
 *
 * Nothing here writes. Progress lives in [ProgressDb], which is why rebuilding
 * and reshipping this file never costs the user a streak.
 */
class ContentDb private constructor(private val db: SQLiteDatabase) {

    /**
     * The language questions are asked in.
     *
     * Held here rather than passed to every query because it changes rarely and
     * applies to all of them; [Repo] sets it when the setting changes and
     * reloads whatever is on screen.
     */
    @Volatile
    var language: GlossLanguage = GlossLanguage.INDONESIAN

    companion object {
        private const val ASSET = "content.db"
        private const val LOCAL = "content.db"


        fun open(context: Context): ContentDb {
            val target = File(context.filesDir, LOCAL)
            val packaged = packagedVersion(context)

            // Copy on first run and whenever the APK itself has been replaced.
            //
            // Keyed on the install timestamp rather than the version code,
            // because the deck's schema travels with the code that queries it:
            // add a column in pipeline/schema.sql, install without bumping the
            // version, and the new SQL runs against the old copied file and
            // throws "no such column" on the first screen. The install time
            // changes on every install, release and debug alike, which is
            // exactly when the asset could have changed.
            if (!target.exists() || installedVersion(context) != packaged) {
                context.assets.open(ASSET).use { input ->
                    target.outputStream().use { input.copyTo(it) }
                }
                markInstalled(context, packaged)
            }

            return ContentDb(
                SQLiteDatabase.openDatabase(
                    target.path, null, SQLiteDatabase.OPEN_READONLY
                )
            )
        }

        private fun prefs(context: Context) =
            context.getSharedPreferences("yybijika", Context.MODE_PRIVATE)

        private fun packagedVersion(context: Context): Long =
            context.packageManager
                .getPackageInfo(context.packageName, 0)
                .lastUpdateTime

        private fun installedVersion(context: Context): Long =
            prefs(context).getLong("content_installed_at", -1)

        private fun markInstalled(context: Context, version: Long) {
            prefs(context).edit().putLong("content_installed_at", version).apply()
        }
    }

    fun close() = db.close()

    fun wordCount(): Int = db.rawQuery("SELECT COUNT(*) FROM word", null).use {
        if (it.moveToFirst()) it.getInt(0) else 0
    }

    /**
     * Every headword and its id.
     *
     * Read once and held: it is 1,173 short strings, and the reading screen
     * needs it for every piece of every line to know which words can be opened.
     */
    val headwords: Map<String, Long> by lazy {
        db.rawQuery("SELECT hanzi, id FROM word", null).use { c ->
            buildMap { while (c.moveToNext()) put(c.getString(0), c.getLong(1)) }
        }
    }

    /** Every word id in the deck, cheapest possible query for session planning. */
    fun allWordIds(): List<Long> =
        db.rawQuery("SELECT id FROM word ORDER BY id", null).use { c ->
            buildList { while (c.moveToNext()) add(c.getLong(0)) }
        }

    /**
     * Load words with everything attached.
     *
     * Done in four queries rather than one join-with-duplicates, because a word
     * with three glosses and two examples would otherwise come back six times
     * and have to be de-duplicated in Kotlin anyway.
     */
    fun bundles(ids: Collection<Long>): List<WordBundle> {
        if (ids.isEmpty()) return emptyList()
        val placeholders = ids.joinToString(",") { "?" }
        val args = ids.map { it.toString() }.toTypedArray()

        // Ordered so the language the learner asked for comes first, which is
        // all "primaryGloss" means. Doing it here rather than in every
        // generator keeps the preference out of the exercise code entirely.
        val glosses = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT word_id, gloss FROM sense WHERE word_id IN ($placeholders) " +
                "ORDER BY word_id, CASE lang WHEN ? THEN 0 ELSE 1 END, ordinal",
            args + language.code,
        ).use { c ->
            while (c.moveToNext()) {
                glosses.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        val notes = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT word_id, note FROM usage_note WHERE word_id IN ($placeholders)", args
        ).use { c ->
            while (c.moveToNext()) {
                notes.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        val examples = mutableMapOf<Long, MutableList<ExampleSentence>>()
        db.rawQuery(
            "SELECT word_id, zh, pinyin, gloss, gloss_en, contains_target, " +
                "token_count, segments FROM example WHERE word_id IN ($placeholders) " +
                "ORDER BY word_id, id", args
        ).use { c ->
            while (c.moveToNext()) {
                examples.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    ExampleSentence(
                        zh = c.getString(1),
                        pinyin = c.getString(2),
                        gloss = c.getString(3),
                        glossEn = c.getString(4),
                        containsTarget = c.getInt(5) == 1,
                        tokenCount = c.getInt(6),
                        preferredGloss = if (language == GlossLanguage.ENGLISH) {
                            c.getString(4) ?: c.getString(3)
                        } else {
                            c.getString(3) ?: c.getString(4)
                        },
                        segments = c.getString(7)
                            ?.split(" ")?.filter { it.isNotBlank() }.orEmpty(),
                    )
                )
            }
        }

        val tags = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT word_id, tag FROM tag WHERE word_id IN ($placeholders)", args
        ).use { c ->
            while (c.moveToNext()) {
                tags.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        // Links are loaded with a join so each one arrives with the other word's
        // reading and meaning: a link you have to look up separately is a link
        // nobody follows.
        val links = mutableMapOf<Long, MutableList<Relation>>()
        db.rawQuery(
            """SELECT r.word_id, r.kind, r.related_hanzi, r.note,
                      w2.pinyin, w2.id IS NOT NULL AS in_deck,
                      (SELECT s.gloss FROM sense s WHERE s.word_id = w2.id
                        AND s.lang = 'id' ORDER BY s.ordinal LIMIT 1) AS gloss
               FROM relation r LEFT JOIN word w2 ON w2.hanzi = r.related_hanzi
               WHERE r.word_id IN ($placeholders)
               ORDER BY r.word_id,
                 CASE r.kind
                   WHEN 'synonym' THEN 1 WHEN 'antonym' THEN 2
                   WHEN 'near-homophone' THEN 3 WHEN 'homophone' THEN 4
                   WHEN 'reversed' THEN 5 WHEN 'measure' THEN 6
                   WHEN 'variant' THEN 7 WHEN 'see-also' THEN 8 ELSE 9 END""",
            args,
        ).use { c ->
            while (c.moveToNext()) {
                links.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    Relation(
                        kind = c.getString(1),
                        hanzi = c.getString(2),
                        note = c.getString(3),
                        pinyin = c.getString(4),
                        gloss = c.getString(6),
                        // 间 and 座 are answers to measure-word questions, not
                        // headwords. A link to one has nothing to open.
                        inDeck = c.getInt(5) == 1,
                    )
                )
            }
        }

        // One join for the whole batch rather than a query per word: the two
        // character exercises need this for every word they are offered.
        val parts = mutableMapOf<Long, MutableList<CharacterPart>>()
        db.rawQuery(
            """SELECT wc.word_id, ch.hanzi, ch.pinyin, ch.gloss, ch.gloss_en,
                      ch.word_count, ch.is_function
               FROM word_character wc JOIN character ch ON ch.hanzi = wc.hanzi
               WHERE wc.word_id IN ($placeholders)
               ORDER BY wc.word_id, wc.position""",
            args,
        ).use { c ->
            while (c.moveToNext()) {
                parts.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    CharacterPart(
                        hanzi = c.getString(1),
                        pinyin = c.getString(2),
                        gloss = c.getString(3),
                        glossEn = c.getString(4),
                        wordCount = c.getInt(5),
                        isFunction = c.getInt(6) == 1,
                        preferredGloss = if (language == GlossLanguage.ENGLISH) {
                            c.getString(4) ?: c.getString(3)
                        } else {
                            c.getString(3) ?: c.getString(4)
                        },
                    )
                )
            }
        }

        return db.rawQuery(
            "SELECT id, hanzi, hanzi_trad, pinyin, pinyin_verified, is_phrase " +
                "FROM word WHERE id IN ($placeholders)", args
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    val id = c.getLong(0)
                    add(
                        WordBundle(
                            id = id,
                            hanzi = c.getString(1),
                            hanziTrad = c.getString(2),
                            pinyin = c.getString(3),
                            pinyinVerified = c.getInt(4) == 1,
                            isPhrase = c.getInt(5) == 1,
                            glosses = glosses[id].orEmpty(),
                            usageNotes = notes[id].orEmpty(),
                            examples = examples[id].orEmpty(),
                            tags = tags[id].orEmpty(),
                            relations = links[id].orEmpty(),
                            characters = parts[id].orEmpty(),
                        )
                    )
                }
            }
        }
    }

    fun bundle(id: Long): WordBundle? = bundles(listOf(id)).firstOrNull()

    /** Words whose hanzi, pinyin or gloss contain the query, for the browse screen. */
    fun search(query: String, limit: Int = 100): List<Long> {
        val like = "%$query%"
        return db.rawQuery(
            """SELECT DISTINCT w.id FROM word w
               LEFT JOIN sense s ON s.word_id = w.id
               WHERE w.hanzi LIKE ? OR w.pinyin LIKE ? OR s.gloss LIKE ?
               ORDER BY w.char_count, w.id LIMIT ?""",
            arrayOf(like, like, like, limit.toString()),
        ).use { c -> buildList { while (c.moveToNext()) add(c.getLong(0)) } }
    }

    /**
     * A pool of candidate distractors: other words the learner might confuse
     * this one with. Same tag where the deck has tags, similar length otherwise.
     */
    fun distractorPool(wordId: Long, charCount: Int, limit: Int = 40): List<WordBundle> {
        // Words sharing a tag come first: same topic, or written in the same
        // stretch of the notes. Four random words out of 1,260 are trivial to
        // tell apart, which makes a multiple-choice question worthless.
        val ids = db.rawQuery(
            """SELECT w.id,
                      MAX(CASE WHEN t.tag IN
                          (SELECT tag FROM tag WHERE word_id = ?) THEN 1 ELSE 0 END) AS related
               FROM word w
               JOIN sense s ON s.word_id = w.id
               LEFT JOIN tag t ON t.word_id = w.id
               WHERE w.id != ?
                 AND ABS(w.char_count - ?) <= 1
               GROUP BY w.id
               ORDER BY related DESC, RANDOM()
               LIMIT ?""",
            arrayOf(
                wordId.toString(), wordId.toString(),
                charCount.toString(), limit.toString(),
            ),
        ).use { c -> buildList { while (c.moveToNext()) add(c.getLong(0)) } }
        return bundles(ids)
    }

    fun passages(): List<Passage> {
        val questions = mutableMapOf<Long, MutableList<PassageQuestion>>()
        db.rawQuery(
            "SELECT passage_id, q, choices_json, answer, explain, kind " +
                "FROM passage_question ORDER BY passage_id, id", null
        ).use { c ->
            while (c.moveToNext()) {
                val raw = org.json.JSONArray(c.getString(2))
                questions.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    PassageQuestion(
                        q = c.getString(1),
                        choices = (0 until raw.length()).map { raw.getString(it) },
                        answer = c.getInt(3),
                        explain = c.getString(4),
                        kind = c.getString(5),
                    )
                )
            }
        }

        val footnotes = mutableMapOf<Long, MutableList<Footnote>>()
        db.rawQuery(
            "SELECT passage_id, phrase, pinyin, note_id, note_en, kind " +
                "FROM passage_footnote ORDER BY passage_id, id", null
        ).use { c ->
            while (c.moveToNext()) {
                footnotes.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    Footnote(
                        phrase = c.getString(1),
                        pinyin = c.getString(2).orEmpty(),
                        note = (if (language == GlossLanguage.ENGLISH) {
                            c.getString(4) ?: c.getString(3)
                        } else {
                            c.getString(3) ?: c.getString(4)
                        }).orEmpty(),
                        kind = c.getString(5),
                    )
                )
            }
        }

        val practises = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT passage_id, hanzi FROM passage_word ORDER BY passage_id, hanzi",
            null,
        ).use { c ->
            while (c.moveToNext()) {
                practises.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        val lines = mutableMapOf<Long, MutableList<PassageLine>>()
        db.rawQuery(
            "SELECT passage_id, zh, pinyin, gloss, gloss_en, segments " +
                "FROM passage_token ORDER BY passage_id, idx", null
        ).use { c ->
            while (c.moveToNext()) {
                lines.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    PassageLine(
                        zh = c.getString(1),
                        pinyin = c.getString(2).orEmpty(),
                        gloss = (if (language == GlossLanguage.ENGLISH) {
                            c.getString(4) ?: c.getString(3)
                        } else {
                            c.getString(3) ?: c.getString(4)
                        }).orEmpty(),
                        // NUL-separated rather than space-separated: a piece
                        // here may be a comma or a quotation mark, and a reading
                        // line stripped of its punctuation reads wrong.
                        // Empty for the older short passages, written before the
                        // segmenter existed; the reader shows those lines whole.
                        //
                        // Each piece is resolved against the deck here rather
                        // than in the reader, so a piece that has no card is
                        // known to be unopenable before anyone can tap it.
                        pieces = c.getString(5)
                            ?.split("\u0000")
                            ?.filter { it.isNotBlank() }
                            ?.map { PassagePiece(it, headwords[it]) }
                            .orEmpty(),
                    )
                )
            }
        }

        return db.rawQuery(
            "SELECT id, title, title_id, title_en, level, translation, " +
                "summary_id, summary_en, tags, char_count, deck_words " +
                "FROM passage ORDER BY char_count, id", null
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    val id = c.getLong(0)
                    val english = language == GlossLanguage.ENGLISH
                    // The older passages stored their translation as one
                    // · separated string with the title first; the newer ones
                    // carry it per line. Only the title still has to be dug out
                    // of the old shape.
                    val legacy = c.getString(5).orEmpty().split(" · ")
                    val zh = lines[id].orEmpty()
                    val withGloss = if (zh.any { it.gloss.isNotBlank() }) zh
                    else zh.mapIndexed { i, line ->
                        line.copy(gloss = legacy.getOrNull(i + 1).orEmpty())
                    }
                    add(
                        Passage(
                            id = id,
                            title = c.getString(1),
                            titleId = (if (english) c.getString(3) else c.getString(2))
                                ?: c.getString(2) ?: legacy.firstOrNull().orEmpty(),
                            level = c.getInt(4),
                            lines = withGloss,
                            questions = questions[id].orEmpty(),
                            footnotes = footnotes[id].orEmpty(),
                            practises = practises[id].orEmpty(),
                            summary = (if (english) c.getString(7) else c.getString(6))
                                ?: c.getString(6) ?: c.getString(7),
                            tags = c.getString(8)
                                ?.split(",")?.filter { it.isNotBlank() }.orEmpty(),
                            charCount = c.getInt(9),
                            deckWords = c.getInt(10),
                        )
                    )
                }
            }
        }
    }

    fun grammarPatterns(): List<GrammarPattern> {
        val examples = mutableMapOf<Long, MutableList<Pair<String, String?>>>()
        db.rawQuery(
            "SELECT pattern_id, zh, pinyin FROM pattern_example ORDER BY pattern_id, id", null
        ).use { c ->
            while (c.moveToNext()) {
                examples.getOrPut(c.getLong(0)) { mutableListOf() }
                    .add(c.getString(1) to c.getString(2))
            }
        }
        return db.rawQuery(
            "SELECT id, formula, note FROM pattern ORDER BY source_page, source_line", null
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    val id = c.getLong(0)
                    add(GrammarPattern(id, c.getString(1), c.getString(2), examples[id].orEmpty()))
                }
            }
        }
    }

    /**
     * How many words could produce each kind of question.
     *
     * Answered in SQL rather than by generating every exercise for every word:
     * the scan was 1,173 words times eight types with a distractor query each,
     * which ran on startup and stalled the first screen. The predicates mirror
     * the Requirement sets in the registry, and a test keeps the two honest.
     */
    fun questionAvailability(): Map<String, Int> = Selectors.byType.mapValues { (_, sql) ->
        db.rawQuery("SELECT COUNT(*) FROM ($sql)", null)
            .use { if (it.moveToFirst()) it.getInt(0) else 0 }
    }


    /**
     * The characters a word is built from, in order, with what each contributes.
     *
     * Loaded per word rather than with the bundle: most screens never show them,
     * and a join on every word in a session would cost more than the one screen
     * that does.
     */
    fun charactersOf(hanzi: String): List<CharacterCard> {
        val ids = hanzi.mapNotNull { ch ->
            ch.takeIf { it.code in 0x4E00..0x9FFF }?.toString()
        }
        if (ids.isEmpty()) return emptyList()
        val placeholders = ids.joinToString(",") { "?" }
        val found = db.rawQuery(
            "SELECT hanzi, pinyin, gloss, gloss_en, word_count FROM character " +
                "WHERE hanzi IN ($placeholders)",
            ids.toTypedArray(),
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    add(
                        CharacterCard(
                            hanzi = c.getString(0),
                            pinyin = c.getString(1),
                            gloss = c.getString(2),
                            glossEn = c.getString(3),
                            wordCount = c.getInt(4),
                        )
                    )
                }
            }
        }.associateBy { it.hanzi }
        // Rebuilt in the word's own order: 出口 and 口出 are different words, and
        // the IN clause comes back in whatever order SQLite likes.
        return ids.mapNotNull { found[it] }
    }

    fun character(hanzi: String): CharacterCard? =
        charactersOf(hanzi).firstOrNull { it.hanzi == hanzi }

    /**
     * Every word in the deck built from this character, commonest use first.
     *
     * This list is the character card's argument for itself: 院 means nothing
     * until 医院, 学院, 商学院 and 工学院 are sitting underneath it.
     */
    fun wordsWith(hanzi: String, limit: Int = 40): List<Triple<Long, String, String?>> =
        db.rawQuery(
            """SELECT w.id, w.hanzi,
                      (SELECT s.gloss FROM sense s WHERE s.word_id = w.id
                        AND s.lang = 'id' ORDER BY s.ordinal LIMIT 1)
               FROM word_character wc JOIN word w ON w.id = wc.word_id
               WHERE wc.hanzi = ?
               ORDER BY length(w.hanzi), w.hanzi
               LIMIT ?""",
            arrayOf(hanzi, limit.toString()),
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    add(Triple(c.getLong(0), c.getString(1), c.getString(2)))
                }
            }
        }

    /**
     * Every character worth rehearsing, commonest first.
     *
     * The ones used in a single word are left out: their card would say nothing
     * the word's own card does not already say.
     */
    fun teachableCharacters(): List<CharacterCard> = db.rawQuery(
        """SELECT hanzi, pinyin, gloss, gloss_en, word_count FROM character
           WHERE word_count >= 2 AND gloss IS NOT NULL AND gloss <> ''
           ORDER BY word_count DESC, hanzi""",
        null,
    ).use { c ->
        buildList {
            while (c.moveToNext()) {
                add(
                    CharacterCard(
                        c.getString(0), c.getString(1), c.getString(2),
                        c.getString(3), c.getInt(4),
                    )
                )
            }
        }
    }

    /** Character meanings to use as wrong answers, never the right one. */
    fun characterDistractors(exclude: String, count: Int): List<CharacterCard> =
        db.rawQuery(
            """SELECT hanzi, pinyin, gloss, gloss_en, word_count FROM character
               WHERE hanzi <> ? AND gloss IS NOT NULL AND word_count >= 2
                 AND is_function = 0
               ORDER BY RANDOM() LIMIT ?""",
            arrayOf(exclude, count.toString()),
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    add(
                        CharacterCard(
                            c.getString(0), c.getString(1), c.getString(2),
                            c.getString(3), c.getInt(4),
                        )
                    )
                }
            }
        }

    /**
     * Every character that appears anywhere in the deck or its examples.
     *
     * The vocabulary a written sentence can reasonably be built from. A
     * character outside it is usually a typo, occasionally a word worth adding
     * to the notes, and never something to fail a sentence over — so it is only
     * ever reported, not enforced.
     */
    fun allCharacters(): Set<Char> {
        val out = mutableSetOf<Char>()
        for (sql in listOf("SELECT hanzi FROM word", "SELECT zh FROM example",
                           "SELECT hanzi FROM character")) {
            db.rawQuery(sql, null).use { c ->
                while (c.moveToNext()) {
                    c.getString(0).forEach { if (it.code in 0x4E00..0x9FFF) out += it }
                }
            }
        }
        return out
    }

    /** Every measure word in the deck, for measure-word distractors. */
    fun measureWords(): List<String> = db.rawQuery(
        """SELECT DISTINCT related_hanzi FROM relation
           WHERE kind = 'measure' AND note LIKE '一' || related_hanzi || '%'""",
        null,
    ).use { c -> buildList { while (c.moveToNext()) add(c.getString(0)) } }

    /**
     * Word ids that can produce one kind of question, in random order.
     *
     * The same predicates as [questionAvailability], returning the rows rather
     * than the count. A single-type quiz used to load a bundle for every word in
     * the deck and then throw away the ones the type could not use, which cost
     * about twelve seconds before the first question appeared.
     */
    fun candidatesFor(typeId: String, limit: Int): List<Long> {
        val where = Selectors.byType[typeId] ?: return emptyList()
        val ids = mutableListOf<Long>()
        db.rawQuery("SELECT word_id FROM ($where) ORDER BY RANDOM() LIMIT ?",
            arrayOf(limit.toString())).use {
            while (it.moveToNext()) ids += it.getLong(0)
        }
        return ids
    }

    fun deckStats(): DeckStats = db.rawQuery(
        """SELECT
             (SELECT COUNT(*) FROM word),
             (SELECT COUNT(*) FROM word_capability WHERE sense_count > 0),
             (SELECT COUNT(*) FROM word WHERE pinyin_verified = 1),
             (SELECT COUNT(*) FROM word_capability WHERE cloze_count > 0)""",
        null,
    ).use {
        if (it.moveToFirst()) {
            DeckStats(it.getInt(0), it.getInt(1), it.getInt(2), it.getInt(3))
        } else {
            DeckStats(0, 0, 0, 0)
        }
    }
}

/**
 * One character, and what it contributes to the words built from it.
 *
 * [wordCount] is how many words in the deck use it, which is also how much the
 * card is worth: a character in one word is a fact about that word, a character
 * in eleven is a piece of the language.
 */
data class CharacterCard(
    val hanzi: String,
    val pinyin: String,
    val gloss: String?,
    val glossEn: String?,
    val wordCount: Int,
) {
    /** Only a character that recurs, and has a meaning, is worth teaching. */
    val teachable: Boolean get() = wordCount >= 2 && !gloss.isNullOrBlank()
}

data class DeckStats(
    val words: Int,
    val withGloss: Int,
    val pinyinVerified: Int,
    val withExample: Int,
)

/** A reading passage with its lines and questions. */
data class Passage(
    val id: Long,
    val title: String,
    val titleId: String,
    val level: Int,
    val lines: List<PassageLine>,
    val questions: List<PassageQuestion>,
    val footnotes: List<Footnote> = emptyList(),
    /**
     * The words from the learner's own notes that this passage uses.
     *
     * The reading section's whole claim, made countable — and the reason a
     * passage is worth finishing even on a day the story is not gripping.
     */
    val practises: List<String> = emptyList(),
    /** The whole passage as prose, for reading it through once at the end. */
    val summary: String? = null,
    val tags: List<String> = emptyList(),
    val charCount: Int = 0,
    val deckWords: Int = 0,
) {
    val comprehension: List<PassageQuestion>
        get() = questions.filter { it.kind == "comprehension" }

    val vocabulary: List<PassageQuestion>
        get() = questions.filter { it.kind == "vocabulary" }

    /** Roughly how long it takes to read, at a learner's pace. */
    val minutes: Int get() = maxOf(1, charCount / 120)
}

/**
 * One piece of a line: a word, or a mark of punctuation.
 *
 * [wordId] is null when the deck has no card for it — most function words, and
 * anything from HSK 1-3 the notes never bothered to write down. Those pieces are
 * still shown, because they are part of the sentence; they are simply not
 * links, which is the difference between a word you can look up and one you
 * cannot.
 */
data class PassagePiece(val text: String, val wordId: Long?) {
    val openable: Boolean get() = wordId != null
}

data class PassageLine(
    val zh: String,
    val pinyin: String,
    val gloss: String,
    /** The line cut into pieces, each knowing whether it can be opened. */
    val pieces: List<PassagePiece> = emptyList(),
)

/**
 * A name, a dish or a turn of phrase the passage leans on.
 *
 * Without these a passage set somewhere real is readable word by word and still
 * opaque: you can parse 黄牛 as "yellow ox" and learn nothing from it.
 */
data class Footnote(
    val phrase: String,
    val pinyin: String,
    val note: String,
    val kind: String,
)

data class PassageQuestion(
    val q: String,
    val choices: List<String>,
    val answer: Int,
    val explain: String?,
    /** 'comprehension' — what it said; 'vocabulary' — what a word meant here. */
    val kind: String = "comprehension",
)

/** A grammar pattern as the notes recorded it, with whatever examples sat under it. */
data class GrammarPattern(
    val id: Long,
    val formula: String,
    val note: String?,
    val examples: List<Pair<String, String?>>,
)
