package io.tr8.yybijika.data

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import io.tr8.yybijika.exercise.ExampleSentence
import io.tr8.yybijika.exercise.WordBundle
import java.io.File

/**
 * Read-only access to the deck that ships with the app.
 *
 * content.db is generated by the Python pipeline, so its schema is defined in
 * pipeline/schema.sql rather than in Kotlin. Reading it with plain SQLite rather
 * than Room is deliberate: Room would want to own the schema and verify it on
 * open, which turns every pipeline change into a migration argument with a file
 * nobody migrates — it is replaced wholesale on each release.
 *
 * Nothing here writes. Progress lives in [ProgressDb], which is why rebuilding
 * and reshipping this file never costs the user a streak.
 */
class ContentDb private constructor(private val db: SQLiteDatabase) {

    companion object {
        private const val ASSET = "content.db"
        private const val LOCAL = "content.db"

        fun open(context: Context): ContentDb {
            val target = File(context.filesDir, LOCAL)
            val packaged = packagedVersion(context)

            // Copy on first run and whenever a release brings a newer deck. The
            // stored version is what tells the two apart; comparing file sizes
            // would miss a same-size content change.
            if (!target.exists() || installedVersion(context) != packaged) {
                context.assets.open(ASSET).use { input ->
                    target.outputStream().use { input.copyTo(it) }
                }
                markInstalled(context, packaged)
            }

            return ContentDb(
                SQLiteDatabase.openDatabase(
                    target.path, null, SQLiteDatabase.OPEN_READONLY
                )
            )
        }

        private fun prefs(context: Context) =
            context.getSharedPreferences("yybijika", Context.MODE_PRIVATE)

        private fun packagedVersion(context: Context): Long =
            context.packageManager
                .getPackageInfo(context.packageName, 0)
                .longVersionCode

        private fun installedVersion(context: Context): Long =
            prefs(context).getLong("content_version", -1)

        private fun markInstalled(context: Context, version: Long) {
            prefs(context).edit().putLong("content_version", version).apply()
        }
    }

    fun close() = db.close()

    fun wordCount(): Int = db.rawQuery("SELECT COUNT(*) FROM word", null).use {
        if (it.moveToFirst()) it.getInt(0) else 0
    }

    /** Every word id in the deck, cheapest possible query for session planning. */
    fun allWordIds(): List<Long> =
        db.rawQuery("SELECT id FROM word ORDER BY id", null).use { c ->
            buildList { while (c.moveToNext()) add(c.getLong(0)) }
        }

    /**
     * Load words with everything attached.
     *
     * Done in four queries rather than one join-with-duplicates, because a word
     * with three glosses and two examples would otherwise come back six times
     * and have to be de-duplicated in Kotlin anyway.
     */
    fun bundles(ids: Collection<Long>): List<WordBundle> {
        if (ids.isEmpty()) return emptyList()
        val placeholders = ids.joinToString(",") { "?" }
        val args = ids.map { it.toString() }.toTypedArray()

        val glosses = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT word_id, gloss FROM sense WHERE word_id IN ($placeholders) " +
                "ORDER BY word_id, ordinal", args
        ).use { c ->
            while (c.moveToNext()) {
                glosses.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        val notes = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT word_id, note FROM usage_note WHERE word_id IN ($placeholders)", args
        ).use { c ->
            while (c.moveToNext()) {
                notes.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        val examples = mutableMapOf<Long, MutableList<ExampleSentence>>()
        db.rawQuery(
            "SELECT word_id, zh, pinyin, gloss, contains_target, token_count " +
                "FROM example WHERE word_id IN ($placeholders)", args
        ).use { c ->
            while (c.moveToNext()) {
                examples.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    ExampleSentence(
                        zh = c.getString(1),
                        pinyin = c.getString(2),
                        gloss = c.getString(3),
                        containsTarget = c.getInt(4) == 1,
                        tokenCount = c.getInt(5),
                    )
                )
            }
        }

        val tags = mutableMapOf<Long, MutableList<String>>()
        db.rawQuery(
            "SELECT word_id, tag FROM tag WHERE word_id IN ($placeholders)", args
        ).use { c ->
            while (c.moveToNext()) {
                tags.getOrPut(c.getLong(0)) { mutableListOf() }.add(c.getString(1))
            }
        }

        return db.rawQuery(
            "SELECT id, hanzi, hanzi_trad, pinyin, pinyin_verified, is_phrase " +
                "FROM word WHERE id IN ($placeholders)", args
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    val id = c.getLong(0)
                    add(
                        WordBundle(
                            id = id,
                            hanzi = c.getString(1),
                            hanziTrad = c.getString(2),
                            pinyin = c.getString(3),
                            pinyinVerified = c.getInt(4) == 1,
                            isPhrase = c.getInt(5) == 1,
                            glosses = glosses[id].orEmpty(),
                            usageNotes = notes[id].orEmpty(),
                            examples = examples[id].orEmpty(),
                            tags = tags[id].orEmpty(),
                        )
                    )
                }
            }
        }
    }

    fun bundle(id: Long): WordBundle? = bundles(listOf(id)).firstOrNull()

    /** Words whose hanzi, pinyin or gloss contain the query, for the browse screen. */
    fun search(query: String, limit: Int = 100): List<Long> {
        val like = "%$query%"
        return db.rawQuery(
            """SELECT DISTINCT w.id FROM word w
               LEFT JOIN sense s ON s.word_id = w.id
               WHERE w.hanzi LIKE ? OR w.pinyin LIKE ? OR s.gloss LIKE ?
               ORDER BY w.char_count, w.id LIMIT ?""",
            arrayOf(like, like, like, limit.toString()),
        ).use { c -> buildList { while (c.moveToNext()) add(c.getLong(0)) } }
    }

    /**
     * A pool of candidate distractors: other words the learner might confuse
     * this one with. Same tag where the deck has tags, similar length otherwise.
     */
    fun distractorPool(wordId: Long, charCount: Int, limit: Int = 40): List<WordBundle> {
        // Words sharing a tag come first: same topic, or written in the same
        // stretch of the notes. Four random words out of 1,260 are trivial to
        // tell apart, which makes a multiple-choice question worthless.
        val ids = db.rawQuery(
            """SELECT w.id,
                      MAX(CASE WHEN t.tag IN
                          (SELECT tag FROM tag WHERE word_id = ?) THEN 1 ELSE 0 END) AS related
               FROM word w
               JOIN sense s ON s.word_id = w.id
               LEFT JOIN tag t ON t.word_id = w.id
               WHERE w.id != ?
                 AND ABS(w.char_count - ?) <= 1
               GROUP BY w.id
               ORDER BY related DESC, RANDOM()
               LIMIT ?""",
            arrayOf(
                wordId.toString(), wordId.toString(),
                charCount.toString(), limit.toString(),
            ),
        ).use { c -> buildList { while (c.moveToNext()) add(c.getLong(0)) } }
        return bundles(ids)
    }

    fun passages(): List<Passage> {
        val questions = mutableMapOf<Long, MutableList<PassageQuestion>>()
        db.rawQuery(
            "SELECT passage_id, q, choices_json, answer, explain FROM passage_question " +
                "ORDER BY passage_id, id", null
        ).use { c ->
            while (c.moveToNext()) {
                val raw = org.json.JSONArray(c.getString(2))
                questions.getOrPut(c.getLong(0)) { mutableListOf() }.add(
                    PassageQuestion(
                        q = c.getString(1),
                        choices = (0 until raw.length()).map { raw.getString(it) },
                        answer = c.getInt(3),
                        explain = c.getString(4),
                    )
                )
            }
        }

        val lines = mutableMapOf<Long, MutableList<Pair<String, String>>>()
        db.rawQuery(
            "SELECT passage_id, zh, pinyin FROM passage_token ORDER BY passage_id, idx", null
        ).use { c ->
            while (c.moveToNext()) {
                lines.getOrPut(c.getLong(0)) { mutableListOf() }
                    .add(c.getString(1) to c.getString(2).orEmpty())
            }
        }

        return db.rawQuery(
            "SELECT id, title, level, translation FROM passage ORDER BY level, id", null
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    val id = c.getLong(0)
                    // The translation is stored as one · separated string, aligned
                    // line for line with the passage, exactly as the notes gloss.
                    val parts = c.getString(3).orEmpty().split(" · ")
                    val glosses = parts.drop(1)
                    val zh = lines[id].orEmpty()
                    add(
                        Passage(
                            id = id,
                            title = c.getString(1),
                            titleId = parts.firstOrNull().orEmpty(),
                            level = c.getInt(2),
                            lines = zh.mapIndexed { i, (text, py) ->
                                PassageLine(text, py, glosses.getOrElse(i) { "" })
                            },
                            questions = questions[id].orEmpty(),
                        )
                    )
                }
            }
        }
    }

    fun grammarPatterns(): List<GrammarPattern> {
        val examples = mutableMapOf<Long, MutableList<Pair<String, String?>>>()
        db.rawQuery(
            "SELECT pattern_id, zh, pinyin FROM pattern_example ORDER BY pattern_id, id", null
        ).use { c ->
            while (c.moveToNext()) {
                examples.getOrPut(c.getLong(0)) { mutableListOf() }
                    .add(c.getString(1) to c.getString(2))
            }
        }
        return db.rawQuery(
            "SELECT id, formula, note FROM pattern ORDER BY source_page, source_line", null
        ).use { c ->
            buildList {
                while (c.moveToNext()) {
                    val id = c.getLong(0)
                    add(GrammarPattern(id, c.getString(1), c.getString(2), examples[id].orEmpty()))
                }
            }
        }
    }

    fun deckStats(): DeckStats = db.rawQuery(
        """SELECT
             (SELECT COUNT(*) FROM word),
             (SELECT COUNT(*) FROM word_capability WHERE sense_count > 0),
             (SELECT COUNT(*) FROM word WHERE pinyin_verified = 1),
             (SELECT COUNT(*) FROM word_capability WHERE cloze_count > 0)""",
        null,
    ).use {
        if (it.moveToFirst()) {
            DeckStats(it.getInt(0), it.getInt(1), it.getInt(2), it.getInt(3))
        } else {
            DeckStats(0, 0, 0, 0)
        }
    }
}

data class DeckStats(
    val words: Int,
    val withGloss: Int,
    val pinyinVerified: Int,
    val withExample: Int,
)

/** A reading passage with its lines and questions. */
data class Passage(
    val id: Long,
    val title: String,
    val titleId: String,
    val level: Int,
    val lines: List<PassageLine>,
    val questions: List<PassageQuestion>,
)

data class PassageLine(val zh: String, val pinyin: String, val gloss: String)

data class PassageQuestion(
    val q: String,
    val choices: List<String>,
    val answer: Int,
    val explain: String?,
)

/** A grammar pattern as the notes recorded it, with whatever examples sat under it. */
data class GrammarPattern(
    val id: Long,
    val formula: String,
    val note: String?,
    val examples: List<Pair<String, String?>>,
)
