"""What each character contributes to the words built from it.

1,173 words are made of 1,012 characters, and 529 of those characters appear in
two or more words. Teaching the words alone teaches 医院, 学院, 商学院 and 工学院 as
four unrelated shapes; teaching 院 once turns them into one idea with four
applications, and makes 法院 guessable the first time it is seen.

These are not dictionary definitions. A dictionary tells you 院 is "a courtyard,
an institution with a yard"; what a learner needs is that 院 is the character on
the end of the big public building, which is the sense that actually predicts
the next word. So each gloss is written to answer "what is this doing in that
word", and the words it appears in are shown beside it on the card.

Characters that are themselves headwords in the notes inherit their meaning from
the word entry rather than being written twice — see characters_for() in build.py.
Everything here is a character the notes never defined on its own.

Indonesian first, then English, to match the word glosses.
"""

from __future__ import annotations

#: Readings that pypinyin gets wrong in isolation, or where the reading the deck
#: actually uses is not the commonest one. A character read alone has no context
#: to disambiguate, which is exactly the case pypinyin handles worst.
READINGS: dict[str, str] = {
    # The reading a character card should lead with is the one that matches the
    # meaning on the card. Where a character genuinely has two live readings in
    # this deck, both are listed, commonest first — a tone drill on 长 that only
    # ever accepted zhǎng would mark 长城 wrong.
    "行": "xíng, háng",      # xíng in 旅行/举行; háng in 银行/行业
    "着": "zhe, zháo",       # the aspect particle, and 着急
    "为": "wèi, wéi",        # wèi in 因为/为了; wéi in 成为
    "得": "dé, de",          # dé to obtain in 得到; de the complement marker
    "地": "dì, de",          # dì ground in 地区; de the adverbial marker
    "重": "zhòng, chóng",    # zhòng heavy in 重要; chóng again in 重新
    "差": "chā, chà",        # chā difference in 差别; chà lacking in 差不多
    "调": "tiáo, diào",      # tiáo to adjust in 调整; diào tone in 声调
    "长": "cháng, zhǎng",    # cháng long in 长城; zhǎng to grow in 长大
    "乐": "lè, yuè",         # lè happy in 快乐; yuè music in 音乐
    "空": "kōng, kòng",      # kōng empty/air in 空运; kòng free time
    "教": "jiào, jiāo",      # jiào in 教师/教室; jiāo to teach in 教书
    "只": "zhǐ, zhī",        # zhǐ only in 只要; zhī the animal measure word
    "了": "le, liǎo",        # le the particle; liǎo in 了解
    "率": "lǜ, shuài",       # lǜ rate in 倍率; shuài to lead
    "藏": "cáng, zàng",      # cáng to hide; Zàng only in 西藏
    "省": "shěng, xǐng",     # shěng to save in 省钱
    "参": "cān",             # cān in 参加/参观, not shēn
    "折": "zhé",
}

#: character -> (Indonesian, English)
GLOSSES: dict[str, tuple[str, str]] = {
    # --- the twenty that carry the most words -----------------------------
    "学": ("belajar, ilmu", "study, learning"),
    "不": ("tidak, bukan", "not"),
    "子": ("akhiran benda; anak", "noun suffix; child"),
    "一": ("satu; begitu…", "one; as soon as"),
    "公": ("umum, milik bersama", "public, shared"),
    "生": ("hidup, lahir; pelajar", "life, to be born; student"),
    "业": ("bidang usaha, pekerjaan", "trade, field of work"),
    "大": ("besar", "big"),
    "场": ("lapangan, tempat luas", "field, open ground"),
    "工": ("kerja, teknik", "work, engineering"),
    "院": ("gedung besar, institusi", "large institution, hall"),
    "作": ("membuat, karya", "to make, a work"),
    "了": ("penanda sudah terjadi", "marks a completed action"),
    "到": ("sampai, tiba", "to reach, arrive"),
    "人": ("orang", "person"),
    "理": ("mengatur; nalar", "to manage; reason"),
    "情": ("perasaan, keadaan", "feeling, circumstance"),
    "经": ("melalui, mengelola", "to pass through, to manage"),
    "出": ("keluar, muncul", "to go out, to emerge"),
    "钱": ("uang", "money"),

    # --- 9 to 7 words -----------------------------------------------------
    "事": ("hal, urusan", "matter, affair"),
    "职": ("jabatan, posisi kerja", "post, position"),
    "教": ("mengajar", "to teach"),
    "实": ("nyata, sungguh", "real, actual"),
    "机": ("mesin; kesempatan", "machine; opportunity"),
    "下": ("bawah; sebentar", "below; a short go at something"),
    "师": ("ahli, guru (pelaku)", "master, practitioner"),
    "车": ("kendaraan beroda", "wheeled vehicle"),
    "来": ("datang; ke arah sini", "to come; towards the speaker"),
    "话": ("ucapan, perkataan", "speech, words"),
    "国": ("negara", "country"),
    "定": ("tetap, memastikan", "fixed, to settle"),
    "员": ("anggota, petugas", "member, staff person"),
    "行": ("berjalan, melakukan", "to go, to carry out"),
    "平": ("rata, datar, tenang", "level, even, calm"),
    "打": ("memukul; melakukan", "to hit; to do"),
    "表": ("menyatakan ke luar", "to express outward"),
    "婚": ("pernikahan", "marriage"),
    "用": ("memakai, guna", "to use, use"),
    "难": ("sulit", "difficult"),
    "口": ("mulut, lubang, pintu", "mouth, opening"),
    "上": ("atas; naik", "above; to get on"),
    "语": ("bahasa, tutur", "language, speech"),
    "发": ("mengeluarkan, memunculkan", "to send out, to bring forth"),
    "意": ("maksud, makna", "intent, meaning"),
    "好": ("baik, bagus", "good"),
    "心": ("hati, batin, pusat", "heart, mind, centre"),
    "营": ("mengelola usaha; berkemah", "to run a business; camp"),
    "运": ("bergerak, mengangkut; nasib", "to move, transport; fortune"),
    "要": ("mau, perlu, penting", "to want, to need, important"),

    # --- 6 words ----------------------------------------------------------
    "别": ("lain, beda; jangan", "other, distinct; don't"),
    "单": ("tunggal; lembar daftar", "single; a list or slip"),
    "会": ("bisa; pertemuan", "can; a gathering"),
    "门": ("pintu; cabang bidang", "door; a branch or department"),
    "方": ("cara, arah, pihak", "way, direction, side"),
    "节": ("ruas, bagian; hari raya", "segment, section; festival"),
    "活": ("hidup", "to live, living"),
    "房": ("rumah, ruangan", "house, room"),
    "分": ("membagi; bagian", "to divide; a part"),
    "报": ("melaporkan, mewartakan", "to report, to announce"),
    "感": ("merasa", "to feel"),
    "色": ("warna; rupa", "colour; appearance"),
    "习": ("membiasakan, berlatih", "to practise, to habituate"),
    "新": ("baru", "new"),
    "球": ("bola", "ball"),
    "家": ("rumah, keluarga; ahli", "home, family; an expert"),

    # --- 5 words ----------------------------------------------------------
    "起": ("bangkit, mulai; bersama", "to rise, to start; together"),
    "收": ("menerima, mengumpulkan", "to receive, to collect"),
    "认": ("mengenali, mengakui", "to recognise, to acknowledge"),
    "水": ("air", "water"),
    "金": ("emas, logam, uang", "gold, metal, money"),
    "风": ("angin; gaya", "wind; style"),
    "年": ("tahun, usia", "year, age"),
    "馆": ("gedung tempat umum", "a public building, hall"),
    "应": ("seharusnya; menanggapi", "ought to; to respond"),
    "区": ("wilayah, kawasan", "district, zone"),
    "通": ("tembus, lancar, lalu lintas", "to pass through, traffic"),
    "身": ("badan, diri", "body, self"),
    "护": ("melindungi, menjaga", "to protect, to guard"),
    "游": ("berkeliling, berenang", "to travel about, to swim"),
    "动": ("bergerak", "to move"),
    "假": ("libur; palsu", "holiday; false"),
    "利": ("untung, manfaat, tajam", "profit, benefit, sharp"),
    "确": ("pasti, tepat", "certain, accurate"),
    "天": ("langit; hari", "sky; day"),
    "说": ("berbicara, mengatakan", "to speak, to say"),
    "告": ("memberitahu, mengadukan", "to tell, to report against"),
    "保": ("menjaga, menjamin", "to keep, to guarantee"),
    "司": ("mengurus, mengelola", "to take charge of"),
    "合": ("menyatu, cocok", "to join, to fit"),
    "看": ("melihat, menonton", "to look, to watch"),
    "客": ("tamu, pelanggan", "guest, customer"),
    "法": ("hukum; cara", "law; method"),
    "住": ("tinggal; menetap", "to live, to stay put"),
    "手": ("tangan; orang yang ahli", "hand; a doer"),
    "静": ("tenang, sunyi", "quiet, still"),
    "重": ("berat, penting", "heavy, important"),
    "道": ("jalan; berkata; ajaran", "road; to say; a doctrine"),
    "自": ("sendiri, dari", "self, from"),
    "族": ("kelompok, suku", "group, clan"),
}

GLOSSES.update({
    # --- 4 words ----------------------------------------------------------
    "音": ("bunyi, suara", "sound"),
    "时": ("waktu", "time"),
    "为": ("karena, demi", "because of, for the sake of"),
    "差": ("selisih, beda; kurang", "difference; lacking"),
    "儿": ("anak; akhiran benda", "child; noun suffix"),
    "这": ("ini", "this"),
    "菜": ("sayur, masakan", "vegetable, dish"),
    "招": ("memanggil, merekrut", "to beckon, to recruit"),
    "清": ("jernih, bersih, jelas", "clear, clean"),
    "点": ("titik; memesan; jam", "point; to order; o'clock"),
    "解": ("mengurai, memahami", "to untie, to understand"),
    "有": ("ada, punya", "to have, there is"),
    "照": ("menyinari, memotret", "to shine on, to photograph"),
    "相": ("saling; rupa", "mutually; appearance"),
    "声": ("suara, bunyi", "voice, sound"),
    "部": ("bagian, departemen", "part, department"),
    "达": ("sampai, mencapai", "to reach, to attain"),
    "卡": ("kartu", "card"),
    "证": ("bukti, surat keterangan", "proof, certificate"),
    "么": ("akhiran kata tanya", "question-word ending"),
    "太": ("terlalu; sangat", "too, excessively"),
    "文": ("tulisan, budaya", "writing, culture"),
    "加": ("menambah, ikut", "to add, to join"),
    "校": ("sekolah", "school"),
    "外": ("luar, asing", "outside, foreign"),
    "究": ("menyelidiki sampai dalam", "to investigate thoroughly"),
    "无": ("tanpa, tiada", "without, none"),
    "小": ("kecil", "small"),
    "歌": ("lagu, nyanyian", "song"),
    "然": ("keadaan begitu", "in such a manner"),
    "特": ("khusus, istimewa", "special, particular"),
    "性": ("sifat, jenis kelamin", "nature, quality, sex"),
    "能": ("mampu, tenaga", "able, capacity"),
    "句": ("kalimat", "sentence"),
    "世": ("dunia, zaman", "world, age"),
    "商": ("dagang, berunding", "commerce, to discuss"),
    "主": ("utama; tuan", "main; master"),
    "科": ("cabang ilmu", "branch of study"),
    "任": ("tugas; menjabat; apa pun", "duty; to serve as; any"),
    "样": ("macam, bentuk", "kind, shape"),
    "建": ("membangun, mendirikan", "to build, to establish"),
    "全": ("seluruh, penuh", "whole, complete"),
    "受": ("menerima, mengalami", "to receive, to undergo"),
    "挥": ("mengayunkan, mengerahkan", "to wave, to bring into play"),
    "是": ("adalah, benar", "to be, correct"),
    "恋": ("cinta, rindu", "love, to long for"),
    "私": ("pribadi, swasta", "private"),

    # --- 3 words ----------------------------------------------------------
    "近": ("dekat", "near"),
    "听": ("mendengar", "to listen"),
    "饭": ("nasi, makanan", "cooked rice, a meal"),
    "旅": ("perjalanan", "travel"),
    "着": ("penanda sedang berlangsung", "marks an ongoing state"),
    "那": ("itu", "that"),
    "扫": ("menyapu, memindai", "to sweep, to scan"),
    "现": ("muncul, sekarang", "to appear, present"),
    "没": ("tidak ada, belum", "not have, not yet"),
    "可": ("boleh, bisa", "may, can"),
    "亲": ("akrab, kerabat", "close, kin"),
    "夫": ("suami, laki-laki dewasa", "husband, grown man"),
    "城": ("kota", "city"),
    "西": ("barat", "west"),
    "原": ("asal, semula", "origin, originally"),
    "信": ("percaya; surat", "to trust; a letter"),
    "十": ("sepuluh", "ten"),
    "轻": ("ringan; muda", "light; young"),
    "故": ("sebab; lama; sengaja", "cause; old; deliberate"),
    "知": ("tahu", "to know"),
    "包": ("membungkus; tas", "to wrap; a bag"),
    "气": ("udara, napas; suasana", "air, breath; mood"),
    "流": ("mengalir, arus", "to flow, current"),
    "奖": ("hadiah, penghargaan", "prize, award"),
    "因": ("sebab", "cause"),
    "遇": ("berjumpa, mengalami", "to meet, to encounter"),
    "去": ("pergi", "to go"),
    "研": ("meneliti", "to research"),
    "算": ("menghitung, memperkirakan", "to calculate, to reckon"),
    "青": ("hijau muda, belia", "green-blue, youthful"),
    "安": ("aman, tenang", "safe, at peace"),
    "参": ("ikut serta, meninjau", "to take part, to view"),
    "者": ("orang yang…", "one who does something"),
    "在": ("berada, sedang", "to be at, in the middle of"),
    "名": ("nama, terkenal", "name, renowned"),
    "使": ("menyuruh, memakai; utusan", "to cause, to use; envoy"),
    "典": ("kitab acuan", "a standard reference work"),
    "读": ("membaca", "to read"),
    "导": ("memandu, mengarahkan", "to guide, to direct"),
    "室": ("ruangan", "room"),
    "堂": ("aula, balai", "hall"),
    "空": ("kosong, udara", "empty, air"),
    "调": ("nada; mengatur", "tone; to adjust"),
    "律": ("aturan, hukum", "rule, law"),
    "格": ("pola, standar, petak", "pattern, standard, grid"),
    "足": ("kaki; cukup", "foot; sufficient"),
    "力": ("tenaga, kekuatan", "strength, force"),
    "中": ("tengah, dalam", "middle, within"),
    "量": ("jumlah, takaran", "quantity, measure"),
    "复": ("mengulang, kembali", "to repeat, to return"),
    "三": ("tiga", "three"),
    "位": ("tempat, kedudukan; org (hormat)", "position; polite measure for people"),
    "美": ("indah, bagus", "beautiful"),
    "整": ("rapi, utuh, membereskan", "tidy, whole, to put in order"),
    "体": ("tubuh, wujud", "body, form"),
    "育": ("membesarkan, mendidik", "to raise, to educate"),
    "网": ("jaring, jaringan", "net, network"),
    "修": ("memperbaiki, menempuh", "to repair, to undertake"),
    "款": ("dana; model", "a sum of money; a style"),
    "前": ("depan, sebelum", "front, before"),
    "队": ("barisan, regu", "line, team"),
    "俗": ("kebiasaan umum, awam", "custom, common"),
    "论": ("membahas, berpendapat", "to discuss, to argue"),
    "望": ("memandang jauh, berharap", "to gaze, to hope"),
    "升": ("naik", "to rise"),
    "具": ("perkakas; berwujud", "implement; to possess"),
    "程": ("jarak tempuh, tahapan", "course, stage of a journey"),
    "立": ("berdiri, mendirikan", "to stand, to set up"),
    "官": ("pejabat; perkara resmi", "official; officialdom"),
    "未": ("belum", "not yet"),
    "同": ("sama, bersama", "same, together"),
})

GLOSSES.update({
    # --- 2 words ----------------------------------------------------------
    "草": ("rumput, jerami", "grass, straw"),
    "准": ("tepat; mengizinkan", "accurate; to permit"),
    "备": ("menyiapkan, bekal", "to prepare, provision"),
    "以": ("dengan, untuk; sejak", "by means of; from"),
    "觉": ("merasa, sadar", "to feel, to sense"),
    "许": ("mengizinkan; mungkin", "to allow; perhaps"),
    "亮": ("terang", "bright"),
    "热": ("panas, hangat", "hot, warm"),
    "吵": ("ribut, bertengkar", "noisy, to quarrel"),
    "逛": ("jalan-jalan santai", "to stroll around"),
    "街": ("jalan, pertokoan", "street"),
    "码": ("kode, angka", "code, number"),
    "演": ("memerankan, mempertunjukkan", "to perform"),
    "害": ("merugikan, bahaya", "to harm, harm"),
    "牌": ("papan, kartu, merek", "board, card, brand"),
    "影": ("bayangan, gambar", "shadow, image"),
    "编": ("menyusun, mengarang", "to compile, to compose"),
    "验": ("menguji, membuktikan", "to test, to verify"),
    "北": ("utara", "north"),
    "共": ("bersama, umum", "together, common"),
    "汽": ("uap", "steam, vapour"),
    "误": ("keliru, salah", "mistaken"),
    "便": ("praktis, mudah", "convenient"),
    "我": ("saya", "I, me"),
    "裤": ("celana", "trousers"),
    "功": ("jasa, keberhasilan", "merit, achievement"),
    "料": ("bahan; memperkirakan", "material; to expect"),
    "痛": ("sakit, nyeri", "pain"),
    "期": ("jangka waktu, periode", "period, term"),
    "目": ("mata; butir, daftar", "eye; item"),
    "省": ("menghemat; provinsi", "to economise; province"),
    "际": ("batas, antara", "boundary, between"),
    "其": ("itu, -nya", "its, that"),
    "言": ("perkataan, bahasa", "speech, words"),
    "持": ("memegang, mempertahankan", "to hold, to maintain"),
    "决": ("memutuskan", "to decide"),
    "农": ("pertanian", "agriculture"),
    "友": ("teman", "friend"),
    "命": ("nyawa, hidup; perintah", "life; command"),
    "计": ("menghitung, merencanakan", "to count, to plan"),
    "沉": ("tenggelam, berat, diam", "to sink, heavy, silent"),
    "怀": ("dada, hati; mengandung", "bosom; to harbour"),
    "挣": ("mencari nafkah, berjuang", "to earn, to struggle"),
    "铁": ("besi", "iron"),
    "细": ("halus, teliti", "fine, detailed"),
    "物": ("benda, barang", "thing, object"),
    "园": ("kebun, taman", "garden, grounds"),
    "厦": ("gedung tinggi", "tall building"),
    "龄": ("umur", "age in years"),
    "四": ("empat", "four"),
    "民": ("rakyat, warga", "the people, civil"),
    "油": ("minyak", "oil"),
    "诉": ("memberitahu, menggugat", "to tell, to sue"),
    "处": ("tempat; menangani", "place; to handle"),
    "钟": ("lonceng, jam", "bell, clock"),
    "词": ("kata", "word"),
    "书": ("buku, tulisan", "book, writing"),
    "盒": ("kotak", "box"),
    "付": ("membayar, menyerahkan", "to pay, to hand over"),
    "种": ("jenis; menanam", "kind; to plant"),
    "光": ("cahaya; habis", "light; used up"),
    "适": ("cocok, pas", "suitable"),
    "呼": ("memanggil, menghembus", "to call, to breathe out"),
    "互": ("saling", "mutually"),
    "士": ("orang terpelajar, ahli", "a person of standing"),
    "欢": ("gembira, suka", "joyful, to like"),
    "礼": ("adat sopan, hadiah", "courtesy, gift"),
    "病": ("sakit, penyakit", "illness"),
    "试": ("mencoba, menguji", "to try, to test"),
    "餐": ("santapan, hidangan", "a meal"),
    "店": ("toko", "shop"),
    "衣": ("pakaian", "clothing"),
    "惯": ("terbiasa", "accustomed"),
    "笑": ("tertawa, tersenyum", "to laugh, to smile"),
    "于": ("pada, terhadap", "at, with regard to"),
    "记": ("mencatat, mengingat", "to record, to remember"),
    "鸡": ("ayam", "chicken"),
    "舞": ("tari", "dance"),
    "老": ("tua; sudah lama", "old, long-standing"),
    "板": ("papan; pemilik usaha", "board; a proprietor"),
    "娘": ("perempuan, ibu", "woman, mother"),
    "必": ("harus, pasti", "must, necessarily"),
    "而": ("dan, tetapi (tulisan)", "and, yet (written)"),
    "厨": ("dapur, masak", "kitchen, cooking"),
    "技": ("keterampilan", "skill"),
    "术": ("teknik, seni", "technique, art"),
    "界": ("batas, dunia bidang", "boundary, a world or field"),
    "愿": ("mau, berharap", "willing, to wish"),
    "专": ("khusus, mendalami satu hal", "specialised"),
    "回": ("kembali; kali", "to return; a time"),
    "户": ("pintu; rumah tangga, nasabah", "door; household, account"),
    "消": ("hilang, menghabiskan", "to vanish, to consume"),
    "想": ("berpikir, ingin", "to think, to want"),
    "质": ("mutu, sifat dasar", "quality, substance"),
    "珍": ("berharga, langka", "precious, rare"),
    "宁": ("tenteram", "tranquil"),
    "远": ("jauh", "far"),
    "思": ("berpikir, merenung", "to think, to ponder"),
    "答": ("menjawab", "to answer"),
    "买": ("membeli", "to buy"),
    "助": ("membantu", "to help"),
    "食": ("makanan, makan", "food, to eat"),
    "观": ("memandang, pandangan", "to view, a view"),
    "战": ("perang, bertanding", "war, to fight"),
    "艺": ("seni, keterampilan", "art, craft"),
    "聚": ("berkumpul", "to gather"),
    "团": ("kelompok, bulat", "group, round"),
    "抱": ("memeluk; menyimpan rasa", "to embrace; to hold a feeling"),
    "享": ("menikmati", "to enjoy"),
    "惊": ("terkejut", "startled"),
    "角": ("sudut; peran", "corner; role"),
    "架": ("rak, rangka; berkelahi", "rack, frame; a fight"),
    "月": ("bulan", "moon, month"),
    "医": ("mengobati, kedokteran", "to treat, medicine"),
    "操": ("melatih, mengendalikan", "to drill, to handle"),
    "健": ("sehat, kuat", "healthy, robust"),
    "排": ("menyusun, barisan", "to arrange, a row"),
    "念": ("mengingat, membaca", "to think of, to read aloud"),
    "纸": ("kertas", "paper"),
    "何": ("apa, mana (tulisan)", "what, which (written)"),
    "之": ("-nya, dari (tulisan)", "of (written)"),
    "容": ("memuat, menampung; wajah", "to contain; countenance"),
    "议": ("berunding, usul", "to deliberate, a proposal"),
    "示": ("menunjukkan", "to show, to indicate"),
    "对": ("terhadap; benar; pasangan", "towards; correct; a pair"),
    "象": ("wujud, gambaran", "image, figure"),
    "争": ("berebut, bersaing", "to contend, to compete"),
    "姻": ("ikatan pernikahan", "marital tie"),
    "式": ("cara, bentuk, model", "manner, style"),
    "做": ("membuat, melakukan", "to do, to make"),
    "藏": ("menyimpan, menyembunyikan", "to store, to hide"),
    "伴": ("menemani, pendamping", "to accompany, a companion"),
    "劳": ("bekerja keras, jerih payah", "labour, toil"),
    "良": ("baik, unggul", "good, fine"),
    "妻": ("istri", "wife"),
    "奇": ("aneh, ajaib", "strange, remarkable"),
    "日": ("matahari, hari", "sun, day"),
    "忙": ("sibuk", "busy"),
    "果": ("buah; hasil", "fruit; result"),
    "女": ("perempuan", "female"),
    "顾": ("menoleh, memperhatikan; pelanggan", "to look after; a patron"),
    "险": ("bahaya, risiko", "danger, risk"),
    "传": ("menyampaikan, menular", "to pass on, to spread"),
    "权": ("hak, kekuasaan", "right, authority"),
    "社": ("perkumpulan, masyarakat", "association, society"),
    "乎": ("partikel penegas (tulisan)", "written particle of degree"),
    "男": ("laki-laki", "male"),
    "黄": ("kuning", "yellow"),
    "产": ("menghasilkan, hasil", "to produce, output"),
    "积": ("menumpuk, mengumpulkan", "to accumulate"),
    "就": ("langsung, lalu", "then, right away"),
    "环": ("lingkaran, keliling", "ring, to encircle"),
    "境": ("keadaan sekitar, batas", "surroundings, boundary"),
    "负": ("memikul, menanggung; minus", "to bear; negative"),
    "资": ("modal, dana, sumber daya", "capital, resources"),
    "及": ("mencapai; dan", "to reach; and"),
    "超": ("melampaui", "to exceed"),
    "器": ("alat, perkakas", "device, instrument"),
    "箱": ("peti, kotak besar", "chest, large box"),
    "品": ("barang, mutu", "goods, quality"),
    "装": ("mengisi, memasang; busana", "to load, to fit; attire"),
    "惜": ("sayang, menyayangkan", "to pity, to cherish"),
    "设": ("mendirikan, merancang", "to set up, to design"),
    "后": ("belakang, sesudah", "behind, after"),
    "求": ("meminta, mencari", "to seek, to request"),
    "广": ("luas", "broad, wide"),
    "乐": ("senang, gembira", "happy"),
    "舍": ("pondok, asrama; merelakan", "lodging; to give up"),
    "怎": ("bagaimana", "how"),
    "维": ("memelihara, menjaga", "to maintain"),
    "休": ("istirahat", "to rest"),
    "从": ("dari, sejak", "from, since"),
    "聘": ("mengangkat pegawai", "to engage, to hire"),
    "率": ("angka perbandingan", "rate, ratio"),
    "失": ("kehilangan, gagal", "to lose, to fail"),
    "尊": ("menghormati", "to respect"),
    "责": ("tanggung jawab, menegur", "responsibility, to reproach"),
    "头": ("kepala; ujung", "head; end"),
    "折": ("melipat, patah; diskon", "to fold, to break; a discount"),
    "图": ("gambar, denah; berniat", "picture, chart; to intend"),
})

#: Characters that *are* headwords, but whose meaning inside a compound is not
#: the meaning the notes wrote down for them.
#:
#: 所 is filed in the notes as "the measure word for buildings", which is true
#: of 一所学校 and useless in 事务所, 派出所 and 厕所, where it is simply the place.
#: Inheriting the word entry is right almost everywhere, so these are listed one
#: by one with the divergence stated, rather than the inheritance being dropped.
OVERRIDES: dict[str, tuple[str, str]] = {
    # word sense: the measure word for buildings
    "所": ("tempat, kantor", "place, office"),
    # word sense: the adverbial marker 地
    "地": ("tanah, tempat", "ground, land, place"),
    # word sense: the post-verb complement marker
    "得": ("memperoleh; penanda pelengkap", "to obtain; complement marker"),
    # word sense: the experiential aspect marker 过
    "过": ("melewati, melampaui", "to pass, to go beyond"),
    # word sense: the measure word for long thin things
    "条": ("butir, jalur", "item, strip"),
    # word sense: sleepy
    "困": ("sulit, terkepung", "hard-pressed, hemmed in"),
    # word sense: a quarter of an hour
    "刻": ("mengukir; saat", "to carve; a moment"),
    # word sense: to grow / senior
    "长": ("panjang; tumbuh; kepala", "long; to grow; head of"),
    # word sense: the measure word for flat things
    "张": ("membentangkan, membuka", "to spread open"),
    # word sense: the measure word for letters
    "封": ("menutup, menyegel", "to seal, to close"),
    # word sense: the measure word for garments and matters
    "件": ("butir, perkara", "item, matter"),
    # word sense: the object-fronting marker 把
    "把": ("gagang; menggenggam", "handle; to grasp"),
    # word sense: a plate, and the measure word for dishes
    "盘": ("piringan, cakram", "disc, flat round thing"),
    # word sense: gram
    "克": ("mengatasi; transliterasi bunyi", "to overcome; used for foreign sounds"),
    # word sense: diced pieces of meat
    "丁": ("potongan kecil", "small cube, diced piece"),
    # word sense: late / evening
    "晚": ("malam", "evening, night"),
    # word sense: only / the measure word for animals
    "只": ("hanya", "only"),
    # word sense: by (agent marker)
    "由": ("berasal dari, karena", "from, owing to"),
    # word sense: just now
    "才": ("baru kemudian; bakat", "only then; talent"),
}
