"""The long reading passages.

The six in essays.py are warm-ups: nine or ten lines, one idea, read in a
minute. These are the reading section proper — thirty to forty lines, a story
with a turn in it, and enough of the notes' own vocabulary that finishing one is
an hour of review disguised as something you wanted to do anyway.

Three rules they are written to, and the build enforces the first:

  * Nothing unfamiliar. Every word is either in the notes or in HSK 1-3, so the
    passage can be read rather than decoded. essay_check reports any word that
    is neither, and a report means the sentence gets rewritten — not the word
    imported.
  * A reason to keep reading. A vocabulary list with full stops is not a story.
    Each one has somebody wanting something and something going wrong.
  * Both languages, line by line and whole. Indonesian and English per line for
    study, and as continuous prose for reading it once through at the end.

Footnotes carry what no vocabulary list will: what a 黄牛 actually is, why the
train to Ürümqi takes two nights, what 开斋节 means to the family hosting you.
"""

from __future__ import annotations

LONG_ESSAYS: list[dict] = [

    {
        "id": "L01",
        "title": "面试那天",
        "title_id": "Hari wawancara itu",
        "title_en": "The day of the interview",
        "level": 2,
        "tags": ["work", "story"],
        "summary_id": (
            "Xiao Lin melihat lowongan, mendaftar, dan datang wawancara dengan "
            "gugup. Manajer tidak bertanya soal nilai, melainkan soal satu hal "
            "yang pernah gagal ia kerjakan. Jawaban jujurnya yang membuat ia "
            "diterima."
        ),
        "summary_en": (
            "Xiao Lin sees a job advert, applies, and turns up to the interview "
            "nervous. The manager does not ask about her marks — he asks about "
            "something she once failed at. It is the honest answer that gets her "
            "the job."
        ),
        "lines": [
            ("小林毕业以后找了三个月工作。",
             "Xiao Lin mencari kerja tiga bulan setelah lulus.",
             "Xiao Lin spent three months looking for work after graduating."),
            ("那天早上她在网上看见一个招聘通知。",
             "Pagi itu dia melihat sebuah lowongan di internet.",
             "That morning she saw a job advert online."),
            ("是一家不大的公司，要招一个职员。",
             "Sebuah perusahaan kecil, mencari seorang karyawan.",
             "A small company, looking for one member of staff."),
            ("工资不高，可是写着“有培训，有机会升职”。",
             "Gajinya tidak tinggi, tapi tertulis 'ada pelatihan, ada peluang naik jabatan'.",
             "The pay was low, but it said 'training provided, chance of promotion'."),
            ("她马上报名了。", "Dia langsung mendaftar.", "She applied at once."),
            ("第三天，公司打电话通知她去面试。",
             "Hari ketiga, perusahaan menelepon memberitahu dia untuk wawancara.",
             "On the third day the company rang to tell her to come for an interview."),
            ("面试那天早上，她起得很早，怕堵车。",
             "Pagi hari wawancara, dia bangun sangat pagi karena takut macet.",
             "On the morning of the interview she got up very early, afraid of the traffic."),
            ("她穿了一件干净的白衬衫，带着自己的身份证和学生证。",
             "Dia memakai kemeja putih yang bersih, membawa KTP dan kartu pelajarnya.",
             "She wore a clean white shirt and brought her ID card and student card."),
            ("到了公司，她坐在外面等。",
             "Sampai di perusahaan, dia duduk menunggu di luar.",
             "At the company she sat outside and waited."),
            ("旁边还有四个人，都很年轻，都很安静。",
             "Di sebelahnya ada empat orang lain, semuanya muda, semuanya diam.",
             "Four others were beside her, all young, all quiet."),
            ("小林心里很着急，手也有一点凉。",
             "Hati Xiao Lin cemas, tangannya pun agak dingin.",
             "Xiao Lin was anxious, and her hands were a little cold."),
            ("轮到她的时候，经理请她坐下。",
             "Waktu gilirannya, manajer mempersilakannya duduk.",
             "When it was her turn, the manager asked her to sit down."),
            ("经理没有问她的成绩，也没有问她的学校。",
             "Manajer tidak menanyakan nilainya, tidak juga sekolahnya.",
             "The manager did not ask about her marks, nor about her school."),
            ("他只问了一句：“你做过什么事情，没有做成功？”",
             "Dia hanya bertanya satu kalimat: 'Apa yang pernah kamu kerjakan dan gagal?'",
             "He asked only one thing: 'What have you done that did not work out?'"),
            ("小林愣了一下。", "Xiao Lin tertegun sejenak.", "Xiao Lin froze for a moment."),
            ("她本来准备好了很多话：她多努力，她多认真。",
             "Sebenarnya dia sudah menyiapkan banyak kata: betapa rajin, betapa tekun dirinya.",
             "She had prepared plenty to say: how hard she worked, how serious she was."),
            ("可是这个问题，她没准备。",
             "Tapi pertanyaan ini tidak dia siapkan.",
             "But she had not prepared for this question."),
            ("她想了想，说了实话。",
             "Dia berpikir sebentar, lalu berkata jujur.",
             "She thought, and told the truth."),
            ("“去年我在一家饭馆实习。”",
             "'Tahun lalu saya magang di sebuah rumah makan.'",
             "'Last year I did an internship at a restaurant.'"),
            ("“老板让我管菜单，我改了很多，客人却不满意。”",
             "'Bos menyuruh saya mengurus menu, saya banyak mengubah, tapi pelanggan tidak puas.'",
             "'The boss put me in charge of the menu. I changed a lot, and the customers were not happy.'"),
            ("“我以为新的菜单比旧的好。”",
             "'Saya kira menu baru lebih baik daripada yang lama.'",
             "'I assumed the new menu was better than the old one.'"),
            ("“后来我才明白，我没有问过客人，也没有问过厨师。”",
             "'Belakangan saya baru paham, saya tidak pernah bertanya kepada pelanggan maupun koki.'",
             "'Only later did I understand that I had asked neither the customers nor the cook.'"),
            ("“那件事我一直记着。”",
             "'Hal itu selalu saya ingat.'",
             "'I have not forgotten it.'"),
            ("经理听完，笑了。",
             "Setelah mendengarnya, manajer tersenyum.",
             "The manager listened, and smiled."),
            ("他说：“你是今天第一个承认自己错了的人。”",
             "Dia berkata: 'Kamu orang pertama hari ini yang mengakui dirinya salah.'",
             "He said: 'You are the first person today to admit being wrong.'"),
            ("“别人都告诉我他们多厉害。”",
             "'Yang lain semua memberitahu saya betapa hebatnya mereka.'",
             "'Everyone else told me how good they are.'"),
            ("一个星期以后，小林收到了通知。",
             "Seminggu kemudian, Xiao Lin menerima pemberitahuan.",
             "A week later Xiao Lin got the letter."),
            ("她签了合同，下个月开始上班。",
             "Dia menandatangani kontrak, mulai bekerja bulan depan.",
             "She signed the contract and started the next month."),
            ("工资还是不高。", "Gajinya tetap tidak tinggi.", "The pay was still low."),
            ("可是那天回家的路上，她走得很轻松。",
             "Tapi dalam perjalanan pulang hari itu, langkahnya ringan.",
             "But walking home that day, she felt light."),
        ],
        "footnotes": [
            {
                "phrase": "身份证",
                "en": "The national ID card. Chinese job interviews, bank counters "
                      "and train stations all ask for it; nothing much happens "
                      "without one.",
                "id": "Kartu identitas nasional. Wawancara kerja, loket bank dan "
                      "stasiun kereta di Tiongkok semuanya memintanya.",
                "kind": "culture",
            },
            {
                "phrase": "愣",
                "en": "To freeze for a beat — caught off guard. 愣了一下 is the "
                      "everyday form, stronger than simply 'surprised'.",
                "id": "Tertegun sesaat — kaget sampai diam. Bentuk sehari-harinya "
                      "愣了一下, lebih kuat daripada sekadar 'terkejut'.",
                "kind": "idiom",
            },
            {
                "phrase": "轮到", "kind": "word",
                "en": "For it to be someone's turn. 轮到我了 — my turn.",
                "id": "Tiba giliran seseorang. 轮到我了 — giliran saya.",
            },
            {
                "phrase": "本来", "kind": "word",
                "en": "Originally — what was true or planned before something "
                      "changed it.",
                "id": "Semula — yang benar atau direncanakan sebelum berubah.",
            },
            {
                "phrase": "实话", "kind": "word",
                "en": "The plain truth. 说实话 — to tell the truth.",
                "id": "Perkataan jujur. 说实话 — berkata jujur.",
            },
            {
                "phrase": "签", "kind": "word",
                "en": "To sign. 签合同 — to sign a contract.",
                "id": "Menandatangani. 签合同 — menandatangani kontrak.",
            },
        ],
        "questions": [
            {
                "q": "小林为什么马上报名？",
                "choices": ["因为工资很高", "因为有培训和升职的机会",
                            "因为公司很大", "因为离家很近"],
                "answer": 1,
                "explain": "通知上写着“有培训，有机会升职”，工资其实不高。",
            },
            {
                "q": "面试那天她为什么起得很早？",
                "choices": ["怕堵车", "要买衬衫", "要复习", "要去银行"],
                "answer": 0,
                "explain": "“她起得很早，怕堵车。”",
            },
            {
                "q": "经理问了她什么问题？",
                "choices": ["她的成绩怎么样", "她为什么选这家公司",
                            "她做过什么事情没有成功", "她想要多少工资"],
                "answer": 2,
                "explain": "经理没问成绩也没问学校，只问她哪件事没做成功。",
            },
            {
                "q": "实习的时候，小林做错了什么？",
                "choices": ["她迟到了很多次", "她改菜单以前没问客人和厨师",
                            "她算错了钱", "她和老板吵架了"],
                "answer": 1,
                "explain": "她自己说：“我没有问过客人，也没有问过厨师。”",
            },
            {
                "q": "经理为什么决定要她？",
                "choices": ["她是唯一承认自己错了的人", "她的学校最好",
                            "她要的工资最少", "她认识公司的人"],
                "answer": 0,
                "explain": "“你是今天第一个承认自己错了的人。”",
            },
            {
                "q": "最后一句“她走得很轻松”是什么意思？",
                "choices": ["她走得很快", "她心里放松、高兴",
                            "她没带东西", "她坐车回家"],
                "answer": 1,
                "explain": "轻松在这里说的是心情，不是走路的样子。",
            },
        ],
        "vocab_questions": [
            {
                "q": "“招聘通知”是什么？",
                "choices": ["请客的通知", "公司要人的通知",
                            "学校的通知", "银行的通知"],
                "answer": 1,
                "explain": "招聘＝公司找人；通知＝告诉大家的消息。",
            },
            {
                "q": "文章里的“升职”是什么意思？",
                "choices": ["工作时间变长", "换一家公司",
                            "职位变高", "工资变少"],
                "answer": 2,
                "explain": "升＝往上；职＝职位。",
            },
            {
                "q": "“实习”和“工作”有什么不一样？",
                "choices": ["实习是一边学一边做，常常还是学生",
                            "实习工资更高", "实习不用去公司", "没有不一样"],
                "answer": 0,
                "explain": "实习是在学习阶段进公司做事，为了学经验。",
            },
            {
                "q": "“承认”在这里是什么意思？",
                "choices": ["不同意", "说出那是真的", "问问题", "忘记了"],
                "answer": 1,
                "explain": "承认自己错了＝说出“我错了”是真的。",
            },
        ],
    },
{
        "id": "L02",
        "title": "机场里的黄牛",
        "title_id": "Calo di bandara",
        "title_en": "The tout at the airport",
        "level": 2,
        "tags": ["travel", "story"],
        "summary_id": (
            "Liburan panjang, tiket habis, dan seorang calo menawarkan tiket "
            "pulang-pergi dengan harga dua kali lipat. Ayah hampir membayar "
            "tunai sebelum putrinya menemukan satu huruf yang salah."
        ),
        "summary_en": (
            "A long holiday, no tickets left, and a tout offering a return fare "
            "at twice the price. The father almost pays cash — until his "
            "daughter spots one wrong character."
        ),
        "lines": [
            ("放假以前，爸爸说要带我们去看长城。",
             "Sebelum libur, ayah bilang mau membawa kami melihat Tembok Besar.",
             "Before the holiday, my father said he would take us to see the Great Wall."),
            ("可是他决定得太晚了。",
             "Tapi dia memutuskannya terlalu telat.",
             "But he decided too late."),
            ("那个星期是劳动节，机票早就卖完了。",
             "Minggu itu Hari Buruh, tiket pesawat sudah lama habis terjual.",
             "That week was Labour Day, and the plane tickets had long since sold out."),
            ("我们还是去了机场，想碰碰运气。",
             "Kami tetap pergi ke bandara, mencoba peruntungan.",
             "We went to the airport anyway, to try our luck."),
            ("机场里人特别多，大家都排队。",
             "Di bandara orang sangat banyak, semua mengantre.",
             "The airport was packed, everyone queuing."),
            ("我们排了四十分钟，工作人员说：没有座位了。",
             "Kami mengantre empat puluh menit, petugas bilang: tidak ada kursi lagi.",
             "We queued forty minutes and the staff said: no seats left."),
            ("爸爸站在那儿，一句话也没说。",
             "Ayah berdiri di situ, tidak berkata sepatah pun.",
             "My father stood there and said nothing."),
            ("这时候，一个小伙子走过来了。",
             "Saat itu, seorang pemuda menghampiri.",
             "Just then a young man came over."),
            ("他很客气，问我们要去哪儿。",
             "Dia sangat ramah, bertanya kami mau ke mana.",
             "He was very polite, and asked where we were going."),
            ("爸爸告诉他以后，他笑了。",
             "Setelah ayah memberitahunya, dia tersenyum.",
             "After my father told him, he smiled."),
            ("“我有票，往返的，四张。”",
             "'Saya punya tiket, pulang-pergi, empat lembar.'",
             "'I have tickets. Return, four of them.'"),
            ("“不过要现金，而且比原价贵一倍。”",
             "'Tapi harus tunai, dan dua kali lipat harga aslinya.'",
             "'But it has to be cash, and twice the original price.'"),
            ("妈妈马上说：这是黄牛，不能相信。",
             "Ibu langsung berkata: ini calo, tidak bisa dipercaya.",
             "My mother said at once: he is a tout, he cannot be trusted."),
            ("可是爸爸很着急，他已经答应了我们。",
             "Tapi ayah sangat cemas, dia sudah berjanji kepada kami.",
             "But my father was anxious — he had already promised us."),
            ("他跟着那个人走到旁边，拿出了钱包。",
             "Dia mengikuti orang itu ke samping, mengeluarkan dompetnya.",
             "He followed the man to one side and took out his wallet."),
            ("那个人给爸爸看了四张登机牌。",
             "Orang itu memperlihatkan empat boarding pass kepada ayah.",
             "The man showed my father four boarding passes."),
            ("我站在爸爸后面，也看了一眼。",
             "Aku berdiri di belakang ayah, ikut melihat sekilas.",
             "I stood behind my father and glanced at them too."),
            ("我觉得哪儿不对。",
             "Aku merasa ada yang tidak beres.",
             "Something felt wrong to me."),
            ("登机牌上的名字，姓写错了一个字。",
             "Nama di boarding pass itu, marganya salah satu huruf.",
             "The surname on the boarding pass had one character wrong."),
            ("我拉了拉爸爸的手。",
             "Aku menarik-narik tangan ayah.",
             "I tugged at my father's hand."),
            ("爸爸低头看了很久，脸色变了。",
             "Ayah menunduk lama sekali, wajahnya berubah.",
             "My father looked down for a long time, and his face changed."),
            ("他把钱包放回口袋，说了一句“谢谢，不要了”。",
             "Dia memasukkan dompet kembali ke saku, berkata 'terima kasih, tidak jadi'.",
             "He put the wallet back in his pocket and said 'thank you, no'."),
            ("那个人没有生气，也没有解释，转身就走了。",
             "Orang itu tidak marah, tidak menjelaskan, langsung berbalik pergi.",
             "The man neither got angry nor explained. He turned and left."),
            ("走得很快。", "Pergi dengan cepat.", "Quickly."),
            ("我们那天没去成长城。",
             "Hari itu kami tidak jadi ke Tembok Besar.",
             "We never made it to the Great Wall that day."),
            ("我们在机场吃了快餐，坐了很久。",
             "Kami makan cepat saji di bandara, duduk lama sekali.",
             "We ate fast food at the airport and sat for a long time."),
            ("爸爸有点不好意思。",
             "Ayah agak malu.",
             "My father was a little embarrassed."),
            ("我说：没关系，明年再去。",
             "Aku bilang: tidak apa-apa, tahun depan pergi lagi.",
             "I said: never mind, we will go next year."),
            ("他摸摸我的头，说：你看得比我仔细。",
             "Dia mengelus kepalaku, berkata: kamu lebih teliti daripada aku.",
             "He patted my head and said: you look more carefully than I do."),
            ("那句话我记了很多年。",
             "Kalimat itu kuingat bertahun-tahun.",
             "I remembered that sentence for years."),
        ],
        "footnotes": [
            {
                "phrase": "黄牛", "kind": "culture",
                "en": "Literally 'yellow ox' — a ticket tout. Buys up scarce "
                      "train and concert tickets and resells them at a markup, "
                      "usually in cash and usually just outside the station.",
                "id": "Harfiah 'sapi kuning' — calo tiket. Memborong tiket kereta "
                      "atau konser yang langka lalu menjualnya lebih mahal, "
                      "biasanya tunai dan di luar stasiun.",
            },
            {
                "phrase": "碰碰运气", "kind": "idiom",
                "en": "To try your luck. 碰 is to bump into something; doubling "
                      "the verb makes it casual — 'give it a go'.",
                "id": "Mencoba peruntungan. 碰 artinya berpapasan; pengulangan "
                      "kata kerjanya membuatnya santai — 'coba saja'.",
            },
            {
                "phrase": "原价", "kind": "word",
                "en": "The original price, before any markup or discount.",
                "id": "Harga asli, sebelum ditambah atau didiskon.",
            },
            {
                "phrase": "脸色", "kind": "word",
                "en": "The look on someone's face. 脸色变了 — his expression changed.",
                "id": "Raut wajah. 脸色变了 — wajahnya berubah.",
            },
            {
                "phrase": "转身", "kind": "word",
                "en": "To turn around, usually to leave.",
                "id": "Berbalik badan, biasanya untuk pergi.",
            },
            {
                "phrase": "摸", "kind": "word",
                "en": "To touch or pat. 摸摸头 — to pat someone on the head.",
                "id": "Menyentuh atau mengelus. 摸摸头 — mengelus kepala.",
            },
            {
                "phrase": "字", "kind": "word",
                "en": "A written character. 写错了一个字 — one character written wrong.",
                "id": "Aksara tertulis. 写错了一个字 — satu huruf salah tulis.",
            },
        ],
        "questions": [
            {
                "q": "他们为什么买不到机票？",
                "choices": ["因为没有钱", "因为爸爸决定得太晚，又赶上劳动节",
                            "因为机场关了", "因为他们去错了机场"],
                "answer": 1,
                "explain": "“他决定得太晚了”，那个星期又是劳动节。",
            },
            {
                "q": "那个小伙子要什么样的付钱方式？",
                "choices": ["刷卡", "汇款", "现金", "以后再付"],
                "answer": 2,
                "explain": "“不过要现金”。",
            },
            {
                "q": "妈妈对那个人是什么看法？",
                "choices": ["觉得他很好", "觉得他是黄牛，不能相信",
                            "觉得他是工作人员", "没有看法"],
                "answer": 1,
                "explain": "“这是黄牛，不能相信。”",
            },
            {
                "q": "“我”发现了什么？",
                "choices": ["票是旧的", "登机牌上的姓写错了一个字",
                            "价钱写错了", "日子不对"],
                "answer": 1,
                "explain": "“登机牌上的名字，姓写错了一个字。”",
            },
            {
                "q": "爸爸最后做了什么？",
                "choices": ["买了票", "报警了", "没有买，说了“谢谢，不要了”",
                            "跟那个人吵架了"],
                "answer": 2,
                "explain": "他把钱包放回口袋，拒绝了。",
            },
            {
                "q": "那个人为什么马上就走了？",
                "choices": ["他还有别的客人", "他生气了",
                            "他怕被发现票是假的", "他要去登机"],
                "answer": 2,
                "explain": "他没有解释也没有生气，走得很快——文章让读者自己想到票有问题。",
            },
            {
                "q": "爸爸最后那句话是什么意思？",
                "choices": ["他觉得女儿看得比他仔细，心里佩服",
                            "他觉得女儿视力好", "他在批评女儿",
                            "他想让女儿以后买票"],
                "answer": 0,
                "explain": "“你看得比我仔细”是夸奖，也是承认自己当时太着急。",
            },
        ],
        "vocab_questions": [
            {
                "q": "“往返”是什么意思？",
                "choices": ["只去不回", "去和回来都有", "换地方", "取消"],
                "answer": 1,
                "explain": "往＝去，返＝回。往返票就是来回票。",
            },
            {
                "q": "“贵一倍”是多少？",
                "choices": ["贵一点", "是原价的两倍", "便宜一半", "一样贵"],
                "answer": 1,
                "explain": "贵一倍＝原来的两倍。",
            },
            {
                "q": "“碰碰运气”在这里是什么意思？",
                "choices": ["撞到人了", "试试看，也许有希望",
                            "运气很好", "买彩票"],
                "answer": 1,
                "explain": "明知道机会不大，还是去试一下。",
            },
            {
                "q": "“不好意思”在最后一段是什么意思？",
                "choices": ["没有意思", "觉得有点丢脸、过意不去",
                            "很生气", "很高兴"],
                "answer": 1,
                "explain": "答应了孩子却没做到，所以觉得过意不去。",
            },
        ],
    },
{
        "id": "L03",
        "title": "去新疆的火车",
        "title_id": "Kereta ke Xinjiang",
        "title_en": "The train to Xinjiang",
        "level": 3,
        "tags": ["travel", "culture"],
        "summary_id": (
            "Dua malam di kereta menuju Xinjiang. Seorang kakek Uighur "
            "menawarkan roti, seorang mahasiswa Kazakh menyanyikan lagu rakyat, "
            "dan penulis sadar bahwa 'Tiongkok' jauh lebih luas daripada yang "
            "diajarkan buku pelajarannya."
        ),
        "summary_en": (
            "Two nights on the train to Xinjiang. An old Uighur man offers "
            "bread, a Kazakh student sings a folk song, and the writer realises "
            "that 'China' is a great deal wider than the textbook said."
        ),
        "lines": [
            ("我一直想去新疆，可是一直没去。",
             "Aku selalu ingin ke Xinjiang, tapi tak pernah jadi.",
             "I had always wanted to go to Xinjiang, and never had."),
            ("同事说：坐飞机四个小时就到了。",
             "Rekan kerja bilang: naik pesawat empat jam sudah sampai.",
             "A colleague said: it is four hours by plane."),
            ("我说：我要坐火车。",
             "Aku bilang: aku mau naik kereta.",
             "I said: I want to take the train."),
            ("他觉得我不太正常。",
             "Dia merasa aku agak tidak waras.",
             "He thought there was something wrong with me."),
            ("火车要走两个晚上。",
             "Kereta itu berjalan dua malam.",
             "The train takes two nights."),
            ("我买了票，带了一本书和很多水。",
             "Aku membeli tiket, membawa sebuah buku dan banyak air.",
             "I bought a ticket and brought a book and a lot of water."),
            ("车厢里人不多，大家很快就熟悉了。",
             "Di gerbong tidak banyak orang, semuanya cepat akrab.",
             "The carriage was not full, and people got to know each other quickly."),
            ("我旁边坐着一位维吾尔族的老人。",
             "Di sebelahku duduk seorang kakek suku Uighur.",
             "Beside me sat an old Uighur man."),
            ("他不太会说普通话，我也不会说他的语言。",
             "Dia kurang bisa bahasa Mandarin, aku pun tak bisa bahasanya.",
             "His Mandarin was poor, and I did not speak his language."),
            ("可是他一直对我笑。",
             "Tapi dia terus tersenyum padaku.",
             "But he kept smiling at me."),
            ("第二天早上，他从袋子里拿出了馕，递给我一块。",
             "Pagi kedua, dia mengeluarkan nan dari kantong, menyodorkan sepotong padaku.",
             "On the second morning he took nan bread from his bag and handed me a piece."),
            ("我说谢谢，他摆摆手，好像这不是什么事。",
             "Aku bilang terima kasih, dia melambaikan tangan, seolah ini bukan apa-apa.",
             "I said thank you; he waved it away, as if it were nothing."),
            ("馕很硬，可是越吃越香。",
             "Nan itu keras, tapi makin dimakan makin sedap.",
             "The bread was hard, and the more I ate the better it tasted."),
            ("下午，对面来了一个哈萨克族的大学生。",
             "Sore hari, di seberang datang seorang mahasiswa suku Kazakh.",
             "In the afternoon a Kazakh university student sat opposite."),
            ("他在内地读书，放假回家。",
             "Dia kuliah di daratan dalam, pulang saat libur.",
             "He studied in inland China and was going home for the holiday."),
            ("他的普通话很流利，还会三种语言。",
             "Bahasa Mandarinnya lancar, dan dia menguasai tiga bahasa.",
             "His Mandarin was fluent, and he spoke three languages."),
            ("我问他：在内地习惯吗？",
             "Aku bertanya: betah di daratan dalam?",
             "I asked him: are you used to it inland?"),
            ("他想了想说：习惯了，可是想家。",
             "Dia berpikir lalu berkata: sudah terbiasa, tapi rindu rumah.",
             "He thought and said: I am used to it, but I miss home."),
            ("他说他们那儿的风俗跟这边不一样。",
             "Dia bilang adat di daerahnya berbeda dengan di sini.",
             "He said the customs where he is from are not the same as here."),
            ("开斋节的时候，一条街的人都互相请客。",
             "Waktu Idul Fitri, orang sekampung saling mengundang makan.",
             "At the end of Ramadan, a whole street of people invite each other in."),
            ("晚上，车厢里很安静。",
             "Malam hari, gerbong sangat sunyi.",
             "At night the carriage was quiet."),
            ("那个大学生忽然轻轻地唱起了一首民歌。",
             "Mahasiswa itu tiba-tiba menyanyikan sebuah lagu rakyat dengan lirih.",
             "The student suddenly began, softly, to sing a folk song."),
            ("是《达坂城的姑娘》。",
             "Lagunya 'Gadis Dabancheng'.",
             "It was 'The Girls of Dabancheng'."),
            ("那位老人也跟着哼。",
             "Kakek itu pun ikut bersenandung.",
             "The old man hummed along."),
            ("我一句歌词也听不懂，可是眼睛有点热。",
             "Aku tak paham satu pun liriknya, tapi mataku terasa panas.",
             "I did not understand a word of it, and my eyes stung."),
            ("第三天早上，窗外全变了。",
             "Pagi hari ketiga, di luar jendela semuanya berubah.",
             "On the third morning everything outside the window had changed."),
            ("没有楼，没有广告，只有很远很远的山。",
             "Tak ada gedung, tak ada iklan, hanya gunung yang jauh sekali.",
             "No buildings, no advertising, only mountains a very long way off."),
            ("我忽然明白同事为什么不懂我。",
             "Aku tiba-tiba paham kenapa rekan kerjaku tak mengerti aku.",
             "I suddenly understood why my colleague had not understood me."),
            ("坐飞机的人看见的是两个地方。",
             "Orang yang naik pesawat melihat dua tempat.",
             "People who fly see two places."),
            ("坐火车的人看见的是中间。",
             "Orang yang naik kereta melihat yang di antaranya.",
             "People who take the train see what is in between."),
        ],
        "footnotes": [
            {
                "phrase": "馕", "kind": "culture",
                "en": "Nan — the flat, hard-baked bread of Xinjiang, cooked on "
                      "the wall of a clay oven. It keeps for days, which is why "
                      "it travels.",
                "id": "Nan — roti pipih khas Xinjiang yang dipanggang di dinding "
                      "tungku tanah liat. Tahan berhari-hari, itulah sebabnya "
                      "dibawa bepergian.",
            },
            {
                "phrase": "内地", "kind": "culture",
                "en": "The interior — how people in Xinjiang, Tibet and Hong Kong "
                      "refer to the rest of mainland China. Geography, and also "
                      "a little distance.",
                "id": "Daratan dalam — sebutan orang Xinjiang, Tibet dan Hong Kong "
                      "untuk wilayah Tiongkok lainnya. Soal geografi, sekaligus "
                      "sedikit jarak.",
            },
            {
                "phrase": "达坂城", "kind": "culture",
                "en": "Dabancheng, a windy town near Ürümqi. 'The Girls of "
                      "Dabancheng' is probably the best-known Uighur folk song in "
                      "China; almost everyone can hum it.",
                "id": "Dabancheng, kota berangin dekat Ürümqi. 'Gadis Dabancheng' "
                      "mungkin lagu rakyat Uighur paling terkenal di Tiongkok; "
                      "hampir semua orang bisa menyenandungkannya.",
            },
            {
                "phrase": "普通话", "kind": "word",
                "en": "Standard Mandarin — literally 'the common speech'.",
                "id": "Bahasa Mandarin baku — harfiah 'bahasa umum'.",
            },
            {
                "phrase": "车厢", "kind": "word",
                "en": "A railway carriage.",
                "id": "Gerbong kereta.",
            },
            {
                "phrase": "越", "kind": "idiom",
                "en": "越 A 越 B — the more A, the more B. 越吃越香: the more you "
                      "eat, the better it tastes.",
                "id": "越 A 越 B — makin A makin B. 越吃越香: makin dimakan makin "
                      "sedap.",
            },
            {
                "phrase": "忽然", "kind": "word",
                "en": "Suddenly, without warning.",
                "id": "Tiba-tiba, tanpa aba-aba.",
            },
            {
                "phrase": "姑娘", "kind": "word",
                "en": "A girl, a young woman. Warmer and more old-fashioned than 女孩.",
                "id": "Gadis, perempuan muda. Lebih hangat dan kuno daripada 女孩.",
            },
            {
                "phrase": "哼", "kind": "word",
                "en": "To hum a tune under your breath.",
                "id": "Bersenandung pelan.",
            },
            {
                "phrase": "硬", "kind": "word",
                "en": "Hard, firm — of a thing. Also of a person: stubborn.",
                "id": "Keras — untuk benda. Untuk orang: keras kepala.",
            },
            {
                "phrase": "摆手", "kind": "word",
                "en": "To wave a hand — here, waving away thanks.",
                "id": "Melambaikan tangan — di sini menolak ucapan terima kasih.",
            },
        ],
        "questions": [
            {
                "q": "同事为什么觉得作者不太正常？",
                "choices": ["因为作者要坐两个晚上的火车，不坐飞机",
                            "因为作者不会说普通话", "因为作者没买票",
                            "因为作者带了很多水"],
                "answer": 0,
                "explain": "飞机四个小时就到，作者却要坐两个晚上的火车。",
            },
            {
                "q": "那位老人给了作者什么？",
                "choices": ["水", "一块馕", "一本书", "钱"],
                "answer": 1,
                "explain": "“从袋子里拿出了馕，递给我一块”。",
            },
            {
                "q": "那个大学生为什么在火车上？",
                "choices": ["去内地读书", "放假回家", "去工作", "去旅游"],
                "answer": 1,
                "explain": "“他在内地读书，放假回家。”",
            },
            {
                "q": "他说在内地生活觉得怎么样？",
                "choices": ["完全不习惯", "习惯了，可是想家",
                            "不想回家", "不愿意说"],
                "answer": 1,
                "explain": "“习惯了，可是想家。”",
            },
            {
                "q": "作者听民歌的时候为什么“眼睛有点热”？",
                "choices": ["车厢里太热", "他听懂了歌词",
                            "他被那一刻感动了", "他困了"],
                "answer": 2,
                "explain": "他说自己一句也听不懂，所以感动的不是歌词，是那个时刻。",
            },
            {
                "q": "最后两句想说什么？",
                "choices": ["飞机比火车快",
                            "坐火车能看见两地之间的一切，飞机看不见",
                            "火车票比较便宜", "新疆很远"],
                "answer": 1,
                "explain": "“坐飞机的人看见的是两个地方，坐火车的人看见的是中间。”",
            },
        ],
        "vocab_questions": [
            {
                "q": "“流利”常常用来说什么？",
                "choices": ["说话或者语言很顺", "路很直", "水很多", "人很快"],
                "answer": 0,
                "explain": "普通话很流利＝说得很顺、不卡。",
            },
            {
                "q": "“风俗”是什么意思？",
                "choices": ["天气", "大家长期形成的生活习惯和做法",
                            "风景", "规定"],
                "answer": 1,
                "explain": "风俗是一个地方的人长期形成的习惯，跟法律的规定不一样。",
            },
            {
                "q": "“互相请客”是什么意思？",
                "choices": ["一个人请大家", "你请我，我也请你",
                            "大家一起付钱", "不请客"],
                "answer": 1,
                "explain": "互相＝彼此，双方都做。",
            },
            {
                "q": "“熟悉”在这里是什么意思？",
                "choices": ["食物做好了", "彼此认识、不陌生了",
                            "很累", "很热"],
                "answer": 1,
                "explain": "大家很快就熟悉了＝很快就不陌生了。",
            },
        ],
    },
{
        "id": "L04",
        "title": "那一年的官司",
        "title_id": "Perkara tahun itu",
        "title_en": "The lawsuit that year",
        "level": 3,
        "tags": ["work", "money", "story"],
        "summary_id": (
            "Pabrik kecil paman digugat pelanggan besar karena barang terlambat. "
            "Pengacara muda menemukan satu kalimat dalam kontrak yang tidak "
            "dibaca siapa pun. Perkara dimenangkan, tetapi paman berhenti "
            "menandatangani apa pun tanpa membaca."
        ),
        "summary_en": (
            "My uncle's small factory is sued by a big client over a late "
            "delivery. A young lawyer finds one line in the contract nobody had "
            "read. They win — and my uncle never signs anything unread again."
        ),
        "lines": [
            ("我舅舅有一个小工厂，做了二十年。",
             "Pamanku punya pabrik kecil, sudah dua puluh tahun.",
             "My uncle has had a small factory for twenty years."),
            ("工厂不大，一共十几个职工。",
             "Pabriknya tidak besar, semuanya belasan pekerja.",
             "It is not big — a dozen or so workers in all."),
            ("那一年，他接了一个很大的客户。",
             "Tahun itu, dia mendapat satu pelanggan besar.",
             "That year he took on a very big client."),
            ("合同很厚，他没有仔细看就签了。",
             "Kontraknya tebal, dia menandatangani tanpa membaca teliti.",
             "The contract was thick. He signed it without reading it carefully."),
            ("他说：做生意靠的是人，不是纸。",
             "Katanya: bisnis itu bergantung pada orang, bukan kertas.",
             "He said: business runs on people, not paper."),
            ("那年冬天，运输出了问题。",
             "Musim dingin tahun itu, pengangkutan bermasalah.",
             "That winter something went wrong with the shipping."),
            ("货晚到了十天。",
             "Barang terlambat sepuluh hari.",
             "The goods arrived ten days late."),
            ("客户很生气，要求索赔。",
             "Pelanggan marah, menuntut ganti rugi.",
             "The client was furious and demanded compensation."),
            ("他们要的钱，比舅舅一年赚的还多。",
             "Uang yang mereka minta lebih banyak dari penghasilan paman setahun.",
             "They wanted more than my uncle earned in a year."),
            ("舅舅不同意，他们就告了他。",
             "Paman tidak setuju, lalu mereka menggugatnya.",
             "My uncle refused, so they sued him."),
            ("那是舅舅第一次打官司。",
             "Itu kali pertama paman berperkara di pengadilan.",
             "It was the first time my uncle had been to court."),
            ("他找了一家律师事务所。",
             "Dia mencari sebuah kantor pengacara.",
             "He found a law firm."),
            ("负责他这件事的律师很年轻，看上去还像学生。",
             "Pengacara yang menangani perkaranya sangat muda, masih seperti mahasiswa.",
             "The lawyer handling it was young — he still looked like a student."),
            ("舅舅心里不太放心。",
             "Hati paman kurang tenang.",
             "My uncle was not reassured."),
            ("那个律师没有说什么，只要走了合同。",
             "Pengacara itu tidak banyak bicara, hanya meminta kontraknya.",
             "The lawyer said little, and simply took the contract away."),
            ("三天以后，他打电话来，问了一个问题。",
             "Tiga hari kemudian dia menelepon, menanyakan satu hal.",
             "Three days later he rang with one question."),
            ("“那批货是海运还是空运？”",
             "'Barang itu dikirim lewat laut atau udara?'",
             "'Was that shipment sent by sea or by air?'"),
            ("舅舅说：海运。",
             "Paman menjawab: lewat laut.",
             "My uncle said: by sea."),
            ("律师说：合同里写着，海运遇到天气问题，可以晚十五天。",
             "Pengacara berkata: di kontrak tertulis, pengiriman laut yang kena masalah cuaca boleh terlambat lima belas hari.",
             "The lawyer said: the contract allows fifteen days' delay for sea freight held up by weather."),
            ("那句话在第十一页，很小的字。",
             "Kalimat itu ada di halaman sebelas, hurufnya kecil sekali.",
             "That line was on page eleven, in very small print."),
            ("舅舅从来没读到那儿。",
             "Paman tak pernah membaca sampai situ.",
             "My uncle had never read that far."),
            ("客户的律师也没有。",
             "Pengacara pelanggan pun tidak.",
             "Neither had the client's lawyer."),
            ("开庭那天，舅舅穿了他最好的衣服。",
             "Hari sidang, paman memakai baju terbaiknya.",
             "On the day of the hearing my uncle wore his best clothes."),
            ("工厂的一个老职工去作证，说那十天天气有多坏。",
             "Seorang pekerja lama pabrik bersaksi, menceritakan betapa buruk cuaca sepuluh hari itu.",
             "One of the factory's long-serving workers gave evidence about how bad the weather had been."),
            ("律师说话不多，可是每一句都有用。",
             "Pengacara tidak banyak bicara, tapi setiap kalimatnya berguna.",
             "The lawyer did not say much, but every sentence counted."),
            ("最后，舅舅打赢了官司。",
             "Akhirnya, paman memenangkan perkara.",
             "In the end my uncle won."),
            ("回家的路上，他一直没说话。",
             "Dalam perjalanan pulang, dia diam terus.",
             "He said nothing the whole way home."),
            ("到了门口他才说：我赢了，可是我不是靠自己赢的。",
             "Sampai di depan pintu dia baru berkata: aku menang, tapi bukan karena diriku sendiri.",
             "At the door he finally said: I won, but not on my own account."),
            ("从那以后，他签任何合同都从第一页读到最后一页。",
             "Sejak itu, kontrak apa pun dia baca dari halaman pertama sampai terakhir.",
             "From then on he read every contract from the first page to the last."),
            ("他说：人还是要相信的，纸也是要读的。",
             "Katanya: orang tetap harus dipercaya, kertas juga harus dibaca.",
             "He said: you still have to trust people — and you still have to read the paper."),
        ],
        "footnotes": [
            {
                "phrase": "索赔", "kind": "word",
                "en": "To claim compensation for a loss, usually under a contract "
                      "or an insurance policy.",
                "id": "Menuntut ganti rugi atas kerugian, biasanya berdasarkan "
                      "kontrak atau polis asuransi.",
            },
            {
                "phrase": "开庭", "kind": "word",
                "en": "For a court hearing to open — the day the case is heard.",
                "id": "Sidang dibuka — hari perkara disidangkan.",
            },
            {
                "phrase": "作证", "kind": "word",
                "en": "To give evidence as a witness.",
                "id": "Memberi kesaksian sebagai saksi.",
            },
            {
                "phrase": "这批货", "kind": "word",
                "en": "批 is the measure word for a batch or consignment of goods.",
                "id": "批 adalah kata bantu bilangan untuk satu partai/kiriman barang.",
            },
            {
                "phrase": "签", "kind": "word",
                "en": "To sign. 签合同 — to sign a contract.",
                "id": "Menandatangani. 签合同 — menandatangani kontrak.",
            },
            {
                "phrase": "页", "kind": "word",
                "en": "A page. 第十一页 — page eleven.",
                "id": "Halaman. 第十一页 — halaman sebelas.",
            },
            {
                "phrase": "从来", "kind": "word",
                "en": "Ever, at any time — almost always with a negative: 从来没 "
                      "means 'never once'.",
                "id": "Pernah, sejak dulu — hampir selalu dengan negasi: 从来没 "
                      "berarti 'tidak pernah sekali pun'.",
            },
            {
                "phrase": "字", "kind": "word",
                "en": "A written character; 小字 is small print.",
                "id": "Aksara tertulis; 小字 berarti huruf kecil.",
            },
        ],
        "questions": [
            {
                "q": "舅舅签合同的时候做了什么？",
                "choices": ["请律师看过", "没有仔细看就签了",
                            "改了几句话", "没有签"],
                "answer": 1,
                "explain": "“合同很厚，他没有仔细看就签了。”",
            },
            {
                "q": "客户为什么告舅舅？",
                "choices": ["货的质量不好", "货晚到了十天，舅舅不同意索赔",
                            "舅舅没付钱", "舅舅换了工厂"],
                "answer": 1,
                "explain": "货晚了十天，客户要索赔，舅舅不同意。",
            },
            {
                "q": "舅舅一开始为什么不放心那个律师？",
                "choices": ["因为他要的钱太多", "因为他很年轻，看上去像学生",
                            "因为他不会说普通话", "因为他在别的城市"],
                "answer": 1,
                "explain": "“看上去还像学生”，所以舅舅心里不太放心。",
            },
            {
                "q": "律师发现了什么？",
                "choices": ["客户没有付钱", "合同第十一页写着海运遇到天气可以晚十五天",
                            "货其实没有晚", "客户的律师是假的"],
                "answer": 1,
                "explain": "那句话在第十一页，字很小，两边都没读到。",
            },
            {
                "q": "老职工去法院做什么？",
                "choices": ["作证，说那十天天气很坏", "付钱",
                            "找工作", "送货"],
                "answer": 0,
                "explain": "“去作证，说那十天天气有多坏”。",
            },
            {
                "q": "“我赢了，可是我不是靠自己赢的”是什么意思？",
                "choices": ["他其实输了", "他知道赢是因为律师和合同，不是因为他自己做得好",
                            "他不想赢", "别人替他付了钱"],
                "answer": 1,
                "explain": "他当初没读合同，赢是别人替他补上的。",
            },
            {
                "q": "这个故事最后想说什么？",
                "choices": ["不要相信任何人", "打官司很容易",
                            "相信人和读合同两件事都要做", "小工厂不要接大客户"],
                "answer": 2,
                "explain": "最后一句：“人还是要相信的，纸也是要读的。”",
            },
        ],
        "vocab_questions": [
            {
                "q": "“合同”是什么？",
                "choices": ["一种货", "两边说好、写下来、都要照着做的文件",
                            "一种钱", "一家公司"],
                "answer": 1,
                "explain": "合同写明双方的责任，签了就要照着做。",
            },
            {
                "q": "“打赢官司”是什么意思？",
                "choices": ["打架赢了", "在法院的案子里赢了",
                            "赢了比赛", "赚了钱"],
                "answer": 1,
                "explain": "打官司＝在法院争一个案子；打赢＝赢了这个案子。",
            },
            {
                "q": "“海运”和“空运”的分别是什么？",
                "choices": ["一个走水路，一个走天上", "一个快，一个更快",
                            "一个贵，一个更贵", "没有分别"],
                "answer": 0,
                "explain": "海运走船，空运走飞机。文章里天气影响的是海运。",
            },
            {
                "q": "“负责”在“负责他这件事的律师”里是什么意思？",
                "choices": ["要付钱", "管这件事、要对它承担责任",
                            "很认真", "不同意"],
                "answer": 1,
                "explain": "负责＝这件事归他管，出了事他要承担。",
            },
        ],
    },
]
